/* CharterPrep — dependency-free interaction layer. Curriculum records stay untouched. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),root=$('appRoot');
const paths={chart:'M3 3v18h18M6 15l4-5 4 3 6-8',target:'M12 8a4 4 0 1 0 4 4M21 12a9 9 0 1 1-9-9M12 12l8-8M16 4h4v4',book:'M4 4h7a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4zM14 7a3 3 0 0 1 3-3h4v15h-3a4 4 0 0 0-4 2',calendar:'M4 5h16v16H4zM7 3v4M17 3v4M4 10h16M8 14h2M14 14h2',clock:'M12 8v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0',review:'M3 11a9 9 0 1 1 2 7M3 4v7h7',check:'M5 12l4 4L19 6',focus:'M8 3H3v5M16 3h5v5M3 16v5h5M21 16v5h-5M8 12h8M12 8v8',sync:'M3 11a9 9 0 0 1 15-6l3 3M21 3v5h-5M21 13a9 9 0 0 1-15 6l-3-3M3 21v-5h5',flame:'M12 3c2 5 7 6 7 12a7 7 0 0 1-14 0c0-3 2-5 3-7 0 4 3 4 4-5',flag:'M5 21V3M5 4c5-4 8 4 14 0v10c-6 4-9-4-14 0',play:'M8 5l11 7-11 7z',pause:'M8 5v14M16 5v14',reset:'M3 10a9 9 0 1 1 1 8M3 3v7h7',save:'M4 4h13l3 3v13H4zM8 4v6h8V4M8 20v-6h8v6',note:'M5 3h10l4 4v14H5zM9 11h6M9 15h6',chevron:'M9 5l7 7-7 7',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-2a8 8 0 0 1 16 0v2'};
const icon=(name)=>`<svg class="cp-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.chart}"/></svg>`;
const el=(tag,cls,html)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(html)n.innerHTML=html;return n};
const esc=s=>escapeHtml(String(s??''));
const localDay=d=>{const n=new Date(d??Date.now());return `${n.getFullYear()}-${String(n.getMonth()+1).padStart(2,'0')}-${String(n.getDate()).padStart(2,'0')}`};
const dayNumber=s=>{const a=s.split('-').map(Number);return Date.UTC(a[0],a[1]-1,a[2])/86400000};
const cp=()=>{meta.charterPrep??={};const s=meta.charterPrep;s.completedAt??={};s.reviewDates??={};s.videoNotes??={};s.mockGoal??=78;s.candidate??='Candidate';s.weightYear??='2026';return s};
todayStr=()=>localDay();
completedCount=()=>MODULES.filter(m=>progress[m.id]).length;
const toastEl=el('div','cp-toast');toastEl.id='cpToast';toastEl.hidden=true;toastEl.setAttribute('role','status');document.body.append(toastEl);let toastId;
const toast=msg=>{toastEl.textContent=msg;toastEl.hidden=false;clearTimeout(toastId);toastId=setTimeout(()=>toastEl.hidden=true,4000)};
const writeLocal=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true}catch{toast('Bộ nhớ thiết bị đã đầy hoặc bị khóa. Dữ liệu mới chưa được lưu.');return false}};
const readLocal=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}};
function confirmAction(title,message,action){const d=$('cpConfirm');$('cpConfirmTitle').textContent=title;$('cpConfirmMessage').textContent=message;$('cpConfirmYes').onclick=()=>{d.close();action()};d.showModal()}
const confirmDialog=el('dialog','cp-confirm','<h3 id="cpConfirmTitle"></h3><p id="cpConfirmMessage"></p><div class="cp-confirm-actions"><button class="btn ghost" id="cpConfirmNo">Hủy</button><button class="btn" id="cpConfirmYes">Xác nhận</button></div>');confirmDialog.id='cpConfirm';confirmDialog.setAttribute('aria-labelledby','cpConfirmTitle');document.body.append(confirmDialog);$('cpConfirmNo').onclick=()=>confirmDialog.close();

// Keep each existing control and its user data; arrange the working surface.
const sidebar=root.querySelector('.sidebar'),logout=$('logoutBtn');
sidebar.innerHTML=`<div class="side-brand"><span class="side-mark">${icon('chart')}</span><span>CharterPrep<small>CFA LEVEL 1</small></span></div><div class="side-target" id="cpTarget">TARGET EXAM · CHƯA ĐẶT<br>YOUR NEXT CHAPTER</div><div class="side-caption">WORKSPACE</div><nav>${[['roadmap','target','Roadmap','Lộ trình'],['modules','book','Modules & Topics','Module'],['schedule','calendar','Study Planner','Lịch học'],['mocks','note','Mock Exams','Mock'],['analytics','chart','Study Analytics','Thống kê'],['review','review','Spaced Review','Ôn tập']].map(([id,i,label,short])=>`<a href="#${id}" class="${id==='roadmap'?'active':''}" title="${label}"><span class="nav-icon">${icon(i)}</span><span class="nav-label" data-long="${label}" data-short="${short}">${label}</span>${id==='modules'?'<span class="nav-count">133</span>':''}</a>`).join('')}</nav><div class="side-bottom"><div class="side-sync"><i class="side-sync-dot" id="cpSyncDot"></i><span id="cpSyncLabel">Lưu trên thiết bị</span></div><div class="side-profile"><span class="cp-avatar">C</span><div><strong id="cpCandidateLabel">Candidate</strong><br><small>CFA Level 1</small></div></div></div>`;
sidebar.querySelector('.side-profile').append(logout);logout.title='Đăng xuất';logout.setAttribute('aria-label','Đăng xuất');
const mobileLabels=()=>sidebar.querySelectorAll('[data-long]').forEach(n=>n.textContent=innerWidth<=620?n.dataset.short:n.dataset.long);mobileLabels();addEventListener('resize',mobileLabels);
const header=root.querySelector('.header');header.querySelector('.h-left>div').prepend(el('div','cp-eyebrow','YOUR PATH TO THE CHARTER'));
const topbar=el('div','cp-topbar',`<div class="cp-top-metrics"><div class="cp-top-metric">${icon('calendar')}<span class="cp-top-label">EXAM DAY</span><strong id="cpLiveCountdown">Chưa đặt</strong></div><div class="cp-top-metric">${icon('flame')}<strong id="cpLiveStreak">0 DAY</strong><span class="cp-top-label">STREAK</span></div><div class="cp-top-metric session-metric">${icon('clock')}<span class="cp-top-label">SESSION</span><strong id="cpLiveSession">00:00:00</strong></div></div><div class="cp-top-actions"><button class="btn" id="cpFocusTop">${icon('focus')}<span class="cp-top-focus-label">Focus Mode</span></button><button class="cp-icon-btn" id="cpSyncTop" aria-label="Mở cài đặt đồng bộ" title="Đồng bộ">${icon('sync')}</button><button class="cp-icon-btn cp-profile" id="cpProfileTop" aria-label="Cài đặt hồ sơ">${icon('user')}</button></div>`);root.prepend(topbar);
const stats=el('div','cp-stats',`${[['book','Module đã hoàn thành','cpStatModules','cpStatModulesFoot'],['clock','Thời gian còn lại','cpStatHours','cpStatHoursFoot'],['chart','Nhịp học cần duy trì','cpStatPace','cpStatPaceFoot'],['calendar','Đếm ngược kỳ thi','cpStatExam','cpStatExamFoot']].map(([i,label,id,foot],idx)=>`<div class="cp-stat"><div class="cp-stat-label">${icon(i)}${label}</div><div class="cp-stat-value" id="${id}">—</div><div class="cp-stat-foot" id="${foot}">Đang tính…</div>${idx===0?'<div class="track"><div class="fill" id="cpStatFill"></div></div>':''}</div>`).join('')}`);
const ring=$('ringPct').closest('.card'),timer=$('timerBtn').closest('.card'),mock=$('mockList').closest('.card'),roadmap=$('grid25').closest('.card'),topics=$('topicBreakdown').closest('.card'),modules=$('moduleGroups').closest('.card'),milestonesCard=$('milestoneGrid').closest('.card'),heatmap=$('heatmapGrid').closest('.card'),schedule=$('scheduleList').closest('.card'),journalCard=$('journalInput').closest('.card'),review=$('weeklyReview').closest('.card'),countdown=$('examDateInput').closest('.card'),pace=$('paceBadge').closest('.card'),sync=$('syncCodeInput').closest('.sync-card'),weak=$('weakCard'),goal=root.querySelector('.goal'),footer=root.querySelector('footer');
const deck=el('section','cp-deck');deck.setAttribute('aria-label','Tổng quan học tập');deck.append(ring,timer,mock);
const paceDetails=el('details','cp-pace-details','<summary>Chi tiết nhịp học và dự kiến hoàn thành</summary>');paceDetails.append(pace);
const left=el('div','cp-left-stack');left.append(weak,topics,milestonesCard);const workspace=el('section','cp-workspace');workspace.append(left,modules);
const lower=el('section','cp-lower');lower.append(heatmap,schedule,journalCard,review);
const settings=el('details','cp-settings','<summary>Hồ sơ, ngày thi & đồng bộ thiết bị</summary>');settings.id='settings';const settingsGrid=el('div','cp-settings-grid');settingsGrid.append(countdown,sync);settings.append(settingsGrid);sync.removeAttribute('id');
root.append(header,goal,stats,deck,paceDetails,roadmap,workspace,lower,settings,footer);
root.querySelectorAll(':scope>.row3').forEach(n=>n.remove());
const title=(card,label,i)=>card.querySelector('.card-title').innerHTML=`${icon(i)} ${label}`;
title(ring,'Tiến độ & mức độ ôn tập','target');title(timer,'Phiên học hôm nay','clock');timer.querySelector('.card-title').insertAdjacentHTML('beforeend','<span class="cp-live" id="cpSessionStatus">READY</span>');
const addMock=$('addMockBtn');title(mock,'Mock Exam Insights','chart');mock.querySelector('.card-title').append(addMock);mock.id='mocks';mock.querySelector('.card-title').style.justifyContent='space-between';addMock.textContent='+ Thêm';
title(topics,'Topics & Exam Weight','book');topics.querySelector('.card-title').insertAdjacentHTML('beforeend','<select id="cpWeightYear" class="cp-weight-year" aria-label="Năm trọng số CFA"><option value="2026">2026</option><option value="2027">2027</option></select>');
title(modules,'Module Explorer','book');modules.querySelector('.card-title').insertAdjacentHTML('beforeend','<span id="cpExplorerCount" class="cp-explorer-meta">133 modules</span>');modules.id='modules';
title(milestonesCard,'Milestone Gallery','flag');title(heatmap,'Study Analytics','chart');heatmap.id='analytics';title(schedule,'Study Planner & Time Blocks','calendar');schedule.id='schedule';title(journalCard,'Nhật ký chủ động','note');title(review,'Weekly Spaced Review','review');review.id='review';title(countdown,'Ngày thi & hồ sơ','calendar');
ring.insertAdjacentHTML('beforeend','<div class="cp-distribution" id="cpDistribution"></div>');
const reset=el('button','cp-icon-btn',icon('reset'));reset.id='cpTimerReset';reset.setAttribute('aria-label','Đặt lại phiên chưa lưu');
const oldBtn=$('timerBtn'),newBtn=oldBtn.cloneNode(true);oldBtn.replaceWith(newBtn);const timerActions=el('div','cp-timer-actions');timerActions.append(newBtn,reset);const commit=el('button','btn ghost',icon('save')+' Lưu phiên');commit.id='cpTimerCommit';timerActions.append(commit);$('timerWeek').after(timerActions);
timer.insertAdjacentHTML('beforeend','<div class="cp-today-list" id="cpTodayList"></div>');
mock.querySelector('.card-title').insertAdjacentHTML('afterend','<div class="cp-mock-value" id="cpMockLatest">—<small>%</small></div><div class="cp-mock-note" id="cpMockLatestLabel">Chưa có kết quả mock</div><div id="cpMockBadge" class="cp-mock-badge">Chưa có dữ liệu</div>');
const mockHistory=el('details','cp-mock-history','<summary>Lịch sử kết quả</summary>');mockHistory.append($('mockList'));mock.append(mockHistory);$('mockTrend').setAttribute('viewBox','0 0 300 100');$('mockTrend').setAttribute('role','img');$('mockTrend').after(el('div','cp-mock-axis','<span>Bài đầu tiên</span><span>Bài gần nhất</span>'));
mock.insertAdjacentHTML('beforeend','<label class="cp-mock-goal">Mục tiêu cá nhân <input id="cpMockGoal" type="number" min="1" max="100" step="1" aria-label="Mục tiêu điểm mock"> %</label><div class="cp-source-note">Mức sẵn sàng được so với mục tiêu của bạn, chưa phải xác suất đậu. <a href="https://www.cfainstitute.org/programs/cfa-program/candidate-resources/exam-results" target="_blank" rel="noopener">Cách CFA chấm kết quả ↗</a></div>');
roadmap.querySelector('.card-title').innerHTML=`${icon('calendar')} Study Roadmap <span class="cp-pill"><span id="roadmapTitleDays">25</span> DAYS</span>`;
const roadTools=el('div','cp-road-tools','<div class="cp-tabs" aria-label="Lọc lộ trình"><button data-range="all" aria-pressed="true">Tất cả</button><button data-range="fortnight" aria-pressed="false">Tuần 1 & 2</button><button data-range="mock" aria-pressed="false">Giai đoạn Mock</button></div><span class="cp-pill" id="cpCurrentDay">DAY 01</span>');roadmap.querySelector('.roadmap-head').after(roadTools);
const roadSettings=el('div','cp-road-settings');const daysLabel=el('label','','Số ngày ôn tập');const daysInput=$('totalDaysInput');const newDays=daysInput.cloneNode(true);daysInput.replaceWith(newDays);newDays.max='90';newDays.min='25';newDays.style.width='66px';daysLabel.append(newDays);const startLabel=el('label','','Ngày bắt đầu');startLabel.append($('programStartInput'));roadSettings.append(daysLabel,startLabel);const spreadBtn=el('button','btn ghost','Dàn đều module');spreadBtn.id='cpSpread';roadSettings.append(spreadBtn);roadmap.append(roadSettings);roadmap.querySelectorAll('.countdown-row').forEach(n=>n.remove());roadmap.append($('totalDaysHint'));roadmap.querySelector('.drag-hint').textContent='Kéo module lên một ngày để đổi lịch, hoặc dùng lựa chọn ngày dưới từng module.';
topics.insertAdjacentHTML('beforeend','<div class="cp-source-note">Trọng số theo năm thi. <a href="https://www.cfainstitute.org/programs/cfa-program/candidate-resources/level-i-exam" target="_blank" rel="noopener">Nguồn: CFA Institute ↗</a></div>');
weak.insertAdjacentHTML('afterbegin','<div class="cp-weak-label">PRIORITY FOCUS</div>');
$('scheduleList').classList.add('cp-schedule-scroll');const addPlan=el('button','plan-btn','+ Thêm lịch');schedule.querySelector('.card-title').append(addPlan);schedule.querySelector('.card-title').style.justifyContent='space-between';addPlan.onclick=()=>openPlanner(Math.min(meta.totalDays,currentProgramDay()));
const plannerPicker=el('div','form-row','<label style="font-size:13px;display:flex;align-items:center;gap:12px;width:100%">Ngày học<select id="cpPlannerDay" aria-label="Ngày cần lên lịch"></select></label>');$('plannerOverlay').querySelector('.modal-head').after(plannerPicker);$('cpPlannerDay').onchange=e=>openPlanner(Number(e.target.value));
const heatWrap=el('div','cp-heat-wrap');const heatScroll=heatmap.querySelector('.heatmap-scroll');const dayLabels=el('div','cp-heat-days','<span>CN</span><span></span><span>T3</span><span></span><span>T5</span><span></span><span>T7</span>');heatWrap.append(dayLabels,heatScroll);heatmap.querySelector('.card-title').after(heatWrap);heatmap.insertAdjacentHTML('beforeend','<div class="cp-heat-stats" id="cpHeatStats"></div>');
journalCard.insertAdjacentHTML('beforeend','<div class="cp-journal-controls"><span id="cpJournalStatus">Tự động lưu · hỗ trợ **đậm**, *nghiêng*, danh sách</span><button id="cpJournalPreview">Xem trước</button></div>');const preview=el('div','cp-markdown');preview.hidden=true;preview.id='cpJournalRendered';$('journalInput').after(preview);
review.querySelector('.card-title').insertAdjacentHTML('afterend','<div class="cp-review-summary" id="cpReviewSummary"></div>');
countdown.insertAdjacentHTML('beforeend','<label class="cp-name-field">Tên hiển thị<input id="cpCandidateName" maxlength="40" aria-label="Tên hiển thị"></label>');
const focusList=$('focusList');const focusShell=el('div','cp-focus-shell');const pomo=el('div','cp-pomodoro','<div class="cp-tabs cp-pomo-tabs"><button data-pomo="focus" aria-pressed="true">Tập trung · 25′</button><button data-pomo="break" aria-pressed="false">Nghỉ · 5′</button></div><div class="cp-pomo-ring"><svg viewBox="0 0 190 190" aria-hidden="true"><circle cx="95" cy="95" r="85" fill="none" stroke="#eeecfd" stroke-width="5"/><circle id="cpPomoArc" cx="95" cy="95" r="85" fill="none" stroke="#4338ca" stroke-width="5" stroke-linecap="round" stroke-dasharray="534"/></svg><div class="cp-pomo-clock" id="cpPomoTime">25:00</div></div><div class="cp-pomo-caption" id="cpPomoCaption">MỘT VIỆC MỖI LÚC</div><div class="cp-pomo-actions"><button class="btn" id="cpPomoStart">Bắt đầu</button><button class="btn ghost" id="cpPomoReset">Đặt lại</button></div><div class="cp-pomo-note">Đồng hồ Pomodoro giúp chia phiên tập trung. Dùng “Lưu phiên” trên dashboard để ghi thời gian học.</div>');focusShell.append(pomo,focusList);$('focusOverlay').append(focusShell);
footer.innerHTML='<span>CharterPrep <span style="color:#b0b6c5">/</span> CFA Study Workspace</span><span><b id="footTotal">133</b> modules · <b id="footDone">0 Done</b></span>';
$('lockScreen').querySelector('h2').textContent='CharterPrep';$('lockScreen').querySelector('.lock-icon').innerHTML=icon('chart');document.title='CharterPrep — CFA Study Master Dashboard';

// Sessions persist independently from cloud data and exclude paused time.
clearInterval(timerInterval);timerRunning=false;timerStartTs=null;
let session=readLocal('cfa-cp-session',{segments:[],since:null});if(!Array.isArray(session.segments))session={segments:[],since:null};
const legacy=Number(localStorage.getItem('cfa-timer-start'));if(legacy>0&&!session.since&&!session.segments.length){session.since=legacy;if(writeLocal('cfa-cp-session',session))localStorage.removeItem('cfa-timer-start')}
const sessionMs=()=>session.segments.reduce((sum,p)=>sum+Math.max(0,p[1]-p[0]),0)+(session.since?Math.max(0,Date.now()-session.since):0);
const hhmmss=ms=>{const secs=Math.floor(ms/1000);return [Math.floor(secs/3600),Math.floor(secs/60)%60,secs%60].map(n=>String(n).padStart(2,'0')).join(':')};
const pauseSession=()=>{if(session.since){session.segments.push([session.since,Date.now()]);session.since=null}writeLocal('cfa-cp-session',session)};
newBtn.onclick=()=>{if(session.since)pauseSession();else{session.since=Date.now();writeLocal('cfa-cp-session',session)}updateTimerDisplay()};
reset.onclick=()=>{if(!sessionMs())return;confirmAction('Đặt lại phiên học?','Thời gian trong phiên chưa lưu sẽ được xóa. Nhật ký các phiên đã lưu vẫn được giữ.',()=>{session={segments:[],since:null};writeLocal('cfa-cp-session',session);updateTimerDisplay();toast('Đã đặt lại phiên học.')})};
commit.onclick=()=>{if(sessionMs()<1000)return;pauseSession();for(const [start,end]of session.segments){let cursor=start;while(cursor<end){const boundary=new Date(cursor);boundary.setHours(24,0,0,0);const stop=Math.min(end,boundary.getTime()),minutes=(stop-cursor)/60000,key=localDay(cursor);timeLog[key]=(timeLog[key]||0)+minutes;sessions.push({date:key,startHour:new Date(cursor).getHours(),minutes});cursor=stop}}saveTimeLog();saveSessions();session={segments:[],since:null};writeLocal('cfa-cp-session',session);renderHeatmap();renderGoldenHour();checkMilestones();updateTimerDisplay();toast('Đã lưu thời gian học vào nhật ký.')};
updateTimerDisplay=function(){const duration=sessionMs();$('timerToday').textContent=hhmmss(duration);$('cpLiveSession').textContent=hhmmss(duration);const weekMins=Object.entries(timeLog).filter(([k])=>dayNumber(localDay())-dayNumber(k)>=0&&dayNumber(localDay())-dayNumber(k)<7).reduce((s,[,v])=>s+v,0);$('timerWeek').textContent=`Đã lưu hôm nay: ${fmtHM(timeLog[localDay()]||0)} · 7 ngày: ${fmtHM(weekMins)}`;newBtn.innerHTML=icon(session.since?'pause':'play')+(session.since?' Tạm dừng':duration?' Tiếp tục':' Bắt đầu');newBtn.className='btn';$('cpSessionStatus').textContent=session.since?'LIVE':duration?'PAUSED':'READY';$('cpSessionStatus').classList.toggle('running',!!session.since);commit.disabled=duration<1000;reset.disabled=duration<1000};
let pomState=readLocal('cfa-cp-pomodoro',{phase:'focus',remaining:1500000,end:null});
if(!['focus','break'].includes(pomState.phase))pomState={phase:'focus',remaining:1500000,end:null};
const pomoDuration=()=>pomState.phase==='break'?300000:1500000;
function updatePomo(){let remaining=pomState.end?Math.max(0,pomState.end-Date.now()):pomState.remaining;if(pomState.end&&remaining===0){pomState.end=null;pomState.remaining=0;writeLocal('cfa-cp-pomodoro',pomState);toast(pomState.phase==='focus'?'Hoàn thành 25 phút tập trung. Nghỉ một chút nhé!':'Đã hết giờ nghỉ. Sẵn sàng học tiếp!')}$('cpPomoTime').textContent=hhmmss(remaining).slice(3);$('cpPomoArc').style.strokeDashoffset=String(534*(1-remaining/pomoDuration()));$('cpPomoStart').textContent=pomState.end?'Tạm dừng':remaining===0?'Bắt đầu lại':remaining<pomoDuration()?'Tiếp tục':'Bắt đầu';$('cpPomoCaption').textContent=pomState.phase==='break'?'THƯ GIÃN & NẠP LẠI NĂNG LƯỢNG':'MỘT VIỆC MỖI LÚC';pomo.querySelectorAll('[data-pomo]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.pomo===pomState.phase)))}
$('cpPomoStart').onclick=()=>{if(pomState.end){pomState.remaining=Math.max(0,pomState.end-Date.now());pomState.end=null}else{if(!pomState.remaining)pomState.remaining=pomoDuration();pomState.end=Date.now()+pomState.remaining}writeLocal('cfa-cp-pomodoro',pomState);updatePomo()};
$('cpPomoReset').onclick=()=>{pomState.remaining=pomoDuration();pomState.end=null;writeLocal('cfa-cp-pomodoro',pomState);updatePomo()};
pomo.querySelectorAll('[data-pomo]').forEach(b=>b.onclick=()=>{pomState={phase:b.dataset.pomo,remaining:b.dataset.pomo==='break'?300000:1500000,end:null};writeLocal('cfa-cp-pomodoro',pomState);updatePomo()});

// Honest, date-aware metrics; no generated activity or inferred exam percentile.
updateStreak=function(t){if(meta.lastActiveDate===t)return;meta.streak=meta.lastActiveDate&&dayNumber(t)-dayNumber(meta.lastActiveDate)===1?(meta.streak||0)+1:1;meta.lastActiveDate=t;meta.longestStreak=Math.max(meta.longestStreak||0,meta.streak)};
const displayedStreak=()=>meta.lastActiveDate&&dayNumber(localDay())-dayNumber(meta.lastActiveDate)<=1?(meta.streak||0):0;
const previousToggle=toggleModule;toggleModule=function(id){if(!MODULES.some(m=>m.id===id))return;if(!progress[id])cp().completedAt[id]=new Date().toISOString();else{delete cp().completedAt[id];delete cp().reviewDates[id];delete reviewed[id]}previousToggle(id);saveReviewed();saveMeta()};window.toggleModule=toggleModule;
function neededMetrics(){const done=completedCount(),remaining=TOTAL-done;const today=localDay();const elapsed=meta.programStart?Math.max(0,dayNumber(today)-dayNumber(meta.programStart)):0;const planLeft=Math.max(1,meta.totalDays-elapsed);const examLeft=meta.examDate?dayNumber(meta.examDate)-dayNumber(today):null;const available=examLeft===null?planLeft:Math.max(1,Math.min(planLeft,examLeft));const needed=remaining/available;const expected=meta.programStart?Math.min(TOTAL,Math.max(0,(elapsed/meta.totalDays)*TOTAL)):null;return{done,remaining,elapsed,available,needed,expected,examLeft}}
function renderMetrics(){const m=neededMetrics(),s=cp(),pct=Math.round(m.done/TOTAL*100);header.querySelector('h1').textContent=`Chào mừng trở lại, ${s.candidate}!`;header.querySelector('.sub').textContent=m.remaining?`Còn ${m.remaining} module trên hành trình của bạn. Duy trì ${m.needed.toFixed(1)} module/ngày trong ${m.available} ngày để hoàn thành kế hoạch.`:'Bạn đã hoàn thành toàn bộ 133 module. Dành thời gian cho mock và ôn lại các phần khó.';$('cpCandidateLabel').textContent=s.candidate;$('cpCandidateName').value=s.candidate;$('cpWeightYear').value=s.weightYear;$('cpMockGoal').value=s.mockGoal;
$('cpStatModules').innerHTML=`${m.done} <small>/ ${TOTAL}</small>`;$('cpStatModulesFoot').textContent=`${pct}% lộ trình đã hoàn thành`;$('cpStatFill').style.width=pct+'%';$('cpStatHours').innerHTML=`${(m.remaining*HOURS_PER_MODULE).toFixed(1)} <small>giờ</small>`;$('cpStatHoursFoot').textContent=`Ước tính ${HOURS_PER_MODULE}h/module · ${(m.needed*HOURS_PER_MODULE).toFixed(1)}h/ngày`;$('cpStatPace').innerHTML=`${m.needed.toFixed(1)} <small>mod/ngày</small>`;const delta=m.expected===null?null:m.done-Math.floor(m.expected);$('cpStatPaceFoot').textContent=delta===null?'Đặt ngày bắt đầu để so tiến độ':delta>=0?`Đúng nhịp · +${delta} module so kế hoạch`:`Cần bù ${Math.abs(delta)} module so kế hoạch`;$('cpStatPaceFoot').className='cp-stat-foot '+(delta===null?'':delta>=0?'cp-good':'cp-warn');$('cpStatExam').innerHTML=m.examLeft===null?'— <small>ngày</small>':`${Math.max(0,m.examLeft)} <small>ngày</small>`;$('cpStatExamFoot').textContent=m.examLeft===null?'Đặt ngày thi trong Cài đặt':m.examLeft<0?'Kỳ thi đã qua':m.examLeft<=14?'Giai đoạn ôn tập & mock':'Tiếp tục tích lũy từng module';const ready=MODULES.filter(x=>progress[x.id]&&(cp().reviewDates[x.id]?.length||reviewed[x.id])).length;$('cpDistribution').innerHTML=[['#0ea968','Đã học & ôn',ready],['#f59e0b','Đã học, chưa ôn',m.done-ready],['#c8cedc','Chưa hoàn thành',m.remaining]].map(([c,l,n])=>`<div class="cp-dist-row"><span><i style="background:${c}"></i>${l}</span><strong>${n} mod</strong></div>`).join('');$('cpCurrentDay').textContent=`DAY ${String(Math.min(currentProgramDay(),meta.totalDays)).padStart(2,'0')}`;$('cpTarget').textContent=meta.examDate?`TARGET: ${new Date(meta.examDate+'T00:00:00').toLocaleDateString('en-US',{month:'short',year:'2-digit'}).toUpperCase()} · MOCK GOAL ${s.mockGoal}%`:`CHƯA ĐẶT NGÀY THI · MOCK GOAL ${s.mockGoal}%`;$('cpTodayList').innerHTML=MODULES.filter(x=>progress[x.id]&&cp().completedAt[x.id]&&localDay(cp().completedAt[x.id])===localDay()).map(x=>`<div class="cp-today-item">✓ <span>${esc(x.name)}</span><time>${new Date(cp().completedAt[x.id]).toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</time></div>`).join('')||'<span>Module hoàn thành hôm nay sẽ xuất hiện ở đây.</span>';
}
renderPace=function(){const m=neededMetrics();$('paceFill').style.width=(m.done/TOTAL*100)+'%';$('paceTargetMark').style.left=Math.min(100,(m.expected||0)/TOTAL*100)+'%';$('paceDay').textContent=`Cần ${m.needed.toFixed(1)} module/ngày · ${m.available} ngày còn lại trong kế hoạch`;$('paceActualLbl').textContent=`Đã học: ${m.done}`;$('paceTargetLbl').textContent=m.expected===null?'Chưa đặt ngày bắt đầu':`Kế hoạch: ${Math.floor(m.expected)}`;const on=m.expected!==null&&m.done>=Math.floor(m.expected);$('paceBadge').textContent=m.expected===null?'CHƯA ĐẶT LỊCH':on?'ON TRACK':'CẦN TĂNG NHỊP';$('paceBadge').className='pace-badge '+(on?'pace-ok':'pace-warn');$('projFinish').textContent='Nhịp học được tính từ số module còn lại và hạn gần nhất giữa lộ trình với ngày thi.'};
renderGoldenHour=function(){const sums={};sessions.forEach(x=>{if(Number.isFinite(x.minutes)&&x.minutes>0)sums[x.startHour]=(sums[x.startHour]||0)+x.minutes});const best=Object.entries(sums).sort((a,b)=>b[1]-a[1])[0];$('goldenHourBox').style.display='block';$('goldenHourBox').textContent=sessions.length>=3&&best?`◷ Giờ học quen thuộc: ${String(best[0]).padStart(2,'0')}:00–${String((Number(best[0])+1)%24).padStart(2,'0')}:00 · ${fmtHM(best[1])} đã ghi nhận`:'◷ Lưu ít nhất 3 phiên để xem khung giờ học quen thuộc.'};

// Roadmap and module exploration.
let roadmapRange='all',selectedDay=null;
const abbreviations={'EQUITY INVESTMENT':'EQUITY','CORPORATE ISSUERS':'CORP','FIXED INCOME':'FI','FINANCIAL STATEMENT ANALYSIS':'FSA','DERIVATIVES':'DERIV','PORTFOLIO MANAGEMENT':'PM','ECONOMICS':'ECON','ALTERNATIVE INVESTMENT':'ALT','ETHICS':'ETHICS'};
renderGrid=function(){const grid=$('grid25');grid.replaceChildren();const today=currentProgramDay();for(let d=1;d<=meta.totalDays;d++){const date=dateForDay(d);const isMock=meta.mockDate&&date&&localDay(date)===meta.mockDate;if(roadmapRange==='fortnight'&&d>14)continue;if(roadmapRange==='mock'&&!isMock&&d<=meta.totalDays-7)continue;const mods=modulesForDay(d),done=mods.filter(m=>progress[m.id]).length,status=dayStatus(d);const cell=el('div',`daycell ${status}${d===today?' today':''}${selectedDay===d?' active':''}`);cell.tabIndex=0;cell.setAttribute('role','button');cell.setAttribute('aria-label',`Ngày ${d}, ${done}/${mods.length} module${d===today?', hôm nay':''}${isMock?', ngày thi thử':''}`);cell.title=mods.length?[...new Set(mods.map(m=>m.topic))].join(' · '):'Chưa xếp module';const tags=[...new Set(mods.map(m=>abbreviations[m.topic]||m.topic))];cell.innerHTML=`<span class="cp-day-state ${d===today?'now':''}">${isMock?'⚑':status==='done'?'✓':d===today?'●':''}</span><span class="dlabel">DAY</span><span class="dnum">${String(d).padStart(2,'0')}</span><span class="cp-day-topic">${isMock?'MOCK':tags.slice(0,2).join(' / ')||'—'}</span><span class="dfrac">${done}/${mods.length} Mod</span>`;cell.onclick=()=>{selectedDay=d;$('filterSelect').value='ALL';$('searchInput').value='';renderGrid();renderModules();if(mods.length)scrollToDay(d);else openPlanner(d)};cell.ondragover=e=>{e.preventDefault();cell.classList.add('dragover')};cell.ondragleave=()=>cell.classList.remove('dragover');cell.ondrop=e=>{e.preventDefault();cell.classList.remove('dragover');const id=e.dataTransfer?.getData('text/plain')||draggedModuleId;if(MODULES.some(m=>m.id===id)){moveModuleToDay(id,d);toast(`Đã chuyển module sang Day ${d}.`)}draggedModuleId=null};grid.append(cell)}roadTools.querySelectorAll('[data-range]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.range===roadmapRange)))};
roadTools.querySelectorAll('[data-range]').forEach(b=>b.onclick=()=>{roadmapRange=b.dataset.range;renderGrid()});
newDays.onchange=e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<25||n>90){e.target.value=meta.totalDays;toast('Lộ trình cần từ 25 đến 90 ngày.');return}if(MODULES.some(m=>effectiveDay(m)>n)||Object.keys(timeBlocks).some(d=>Number(d)>n&&timeBlocks[d]?.length)){e.target.value=meta.totalDays;toast('Có module hoặc lịch học nằm sau ngày này. Chuyển lịch trước khi rút ngắn lộ trình.');return}meta.totalDays=n;saveMeta();render();toast(`Đã đặt lộ trình ${n} ngày. Dùng “Dàn đều module” nếu muốn chia lại lịch.`)};
spreadBtn.onclick=()=>confirmAction('Dàn đều lộ trình?',`Chia ${TOTAL} module theo thứ tự gốc trên ${meta.totalDays} ngày. Các khung giờ đã đặt sẽ được chuyển theo module đầu tiên của mỗi khung; khung chỉ có tên giữ nguyên ngày.`,()=>{MODULES.forEach((m,i)=>dayOverride[m.id]=Math.min(meta.totalDays,Math.floor(i*meta.totalDays/TOTAL)+1));const next={};for(const [day,blocks]of Object.entries(timeBlocks))for(const b of blocks){const first=MODULES.find(m=>m.id===b.moduleIds?.[0]);const target=first?effectiveDay(first):Math.min(meta.totalDays,Number(day));(next[target]??=[]).push(b)}timeBlocks=next;saveSchedule();render();toast('Đã dàn đều module trên lộ trình. Kiểm tra khung giờ nếu một buổi có nhiều module.')});
const normalize=s=>s.toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
renderModules=function(){const q=normalize($('searchInput').value.trim()),filter=$('filterSelect').value;const chosen=filter==='ALL'?TOPICS:[filter];let found=0;const html=chosen.map(topic=>{const mods=MODULES.filter(m=>m.topic===topic&&(!q||normalize(m.name).includes(q)));if(!mods.length)return '';found+=mods.length;const count=topicStats(topic);return `<div class="topic-block" data-topic-block="${esc(topic)}"><div class="topic-block-head" role="button" tabindex="0" aria-expanded="${openTopics.has(topic)||!!q}"><div class="left"><span class="count-chip">${count.done}/${count.total}</span><b>${esc(topic)}</b></div><span class="chev ${openTopics.has(topic)||q?'open':''}">›</span></div><div class="module-list ${openTopics.has(topic)||q?'open':''}">${mods.map(m=>`<div class="module-row ${progress[m.id]?'done':''}" data-mid="${m.id}" draggable="true"><button class="chk ${progress[m.id]?'checked':''}" data-complete="${m.id}" role="checkbox" aria-checked="${!!progress[m.id]}" aria-label="Hoàn thành ${esc(m.name)}">${progress[m.id]?'<svg viewBox="0 0 24 24" fill="none"><path d="M4 12l6 6L20 6" stroke="white" stroke-width="3"/></svg>':''}</button><div class="mname">${esc(m.name)}</div><span class="cp-module-day">${progress[m.id]?'✓':''}</span><div class="cp-module-tools"><div class="stars" aria-label="Độ khó">${[1,2,3,4,5].map(n=>`<button class="star ${(difficulty[m.id]||0)>=n?'filled':''}" data-rate="${n}" data-module="${m.id}" aria-label="Độ khó ${n} trên 5: ${esc(m.name)}" aria-pressed="${difficulty[m.id]===n}">★</button>`).join('')}</div><button class="video-btn ${videoLinks[m.id]?'has-video':''}" data-video="${m.id}" aria-label="${videoLinks[m.id]?'Xem':'Gắn'} video cho ${esc(m.name)}" title="${videoLinks[m.id]?'Xem video':'Gắn video YouTube'}">▶</button><select class="day-select" data-schedule="${m.id}" aria-label="Ngày học: ${esc(m.name)}">${Array.from({length:meta.totalDays},(_,i)=>`<option value="${i+1}" ${effectiveDay(m)===i+1?'selected':''}>Day ${String(i+1).padStart(2,'0')}</option>`).join('')}</select></div></div>`).join('')}</div></div>`}).join('');$('moduleGroups').innerHTML=html||'<div class="empty-hint">Không tìm thấy module. Thử mã bài hoặc một từ trong tên bài.</div>';$('cpExplorerCount').textContent=`${found} / ${TOTAL} modules`;
$('moduleGroups').querySelectorAll('.topic-block-head').forEach(h=>h.onclick=()=>toggleTopicOpen(h.parentElement.dataset.topicBlock));$('moduleGroups').querySelectorAll('[data-complete]').forEach(b=>b.onclick=()=>{const id=b.dataset.complete;toggleModule(id);$('moduleGroups').querySelector(`[data-complete="${id}"]`)?.focus()});$('moduleGroups').querySelectorAll('[data-rate]').forEach(b=>b.onclick=()=>{setDifficulty(b.dataset.module,Number(b.dataset.rate));renderWeakCard();$('moduleGroups').querySelector(`[data-module="${b.dataset.module}"][data-rate="${b.dataset.rate}"]`)?.focus()});$('moduleGroups').querySelectorAll('[data-video]').forEach(b=>b.onclick=()=>openVideoModal(b.dataset.video));$('moduleGroups').querySelectorAll('[data-schedule]').forEach(b=>b.onchange=()=>moveModuleToDay(b.dataset.schedule,Number(b.value)));$('moduleGroups').querySelectorAll('[draggable=true]').forEach(row=>{row.ondragstart=e=>{draggedModuleId=row.dataset.mid;e.dataTransfer.setData('text/plain',draggedModuleId);row.classList.add('dragging')};row.ondragend=()=>{draggedModuleId=null;row.classList.remove('dragging')}})};
// Listeners in the original file retain function references: route them to the new renderer too.
$('searchInput').addEventListener('input',()=>renderModules());$('filterSelect').addEventListener('change',()=>renderModules());
const weights={2026:{'ETHICS':'15–20%','QUANTITATIVE METHODS':'6–9%','ECONOMICS':'6–9%','FINANCIAL STATEMENT ANALYSIS':'11–14%','CORPORATE ISSUERS':'6–9%','EQUITY INVESTMENT':'11–14%','FIXED INCOME':'11–14%','DERIVATIVES':'5–8%','ALTERNATIVE INVESTMENT':'7–10%','PORTFOLIO MANAGEMENT':'8–12%'},2027:{'ETHICS':'10–15%','QUANTITATIVE METHODS':'11–14%','ECONOMICS':'6–9%','FINANCIAL STATEMENT ANALYSIS':'11–14%','CORPORATE ISSUERS':'6–9%','EQUITY INVESTMENT':'11–14%','FIXED INCOME':'11–14%','DERIVATIVES':'6–9%','ALTERNATIVE INVESTMENT':'6–9%','PORTFOLIO MANAGEMENT':'8–12%'}};
let expandedTopics=new Set();
renderTopicBreakdown=function(){const year=cp().weightYear;const list=Object.keys(weights[year]||weights[2026]);$('topicBreakdown').innerHTML=list.map((t,i)=>{const s=topicStats(t),isWeak=meta.weakTopics.includes(t);return `<details class="cp-topic" data-weight-topic="${esc(t)}" ${expandedTopics.has(t)?'open':''}><summary><i class="cp-topic-bar" style="background:${TOPIC_COLORS[t]||'#9b8cd8'}"></i><span class="cp-topic-name">${esc(t)}</span><span class="cp-topic-weight">${weights[year][t]}</span><span class="cp-topic-ratio">${s.done}/${s.total}</span></summary><div class="track"><div class="fill" style="width:${s.total?s.done/s.total*100:0}%;background:${TOPIC_COLORS[t]||'#9b8cd8'}"></div></div><div class="cp-topic-detail">${s.total?`${s.total-s.done} module chưa hoàn thành.`:'Chưa có module trong dữ liệu gốc.'}${s.total?`<div class="cp-topic-actions"><button class="btn ghost" data-jump="${esc(t)}">Xem module →</button><button class="weak-toggle ${isWeak?'active':''}" data-weak="${esc(t)}">${isWeak?'Bỏ đánh dấu yếu':'Đánh dấu cần ôn'}</button></div>`:''}</div></details>`}).join('');$('topicBreakdown').querySelectorAll('details').forEach(d=>d.ontoggle=()=>{if(d.open)expandedTopics.add(d.dataset.weightTopic);else expandedTopics.delete(d.dataset.weightTopic)});$('topicBreakdown').querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>{$('filterSelect').value='ALL';$('searchInput').value='';jumpToTopic(b.dataset.jump)});$('topicBreakdown').querySelectorAll('[data-weak]').forEach(b=>b.onclick=()=>toggleWeak(b.dataset.weak))};
$('cpWeightYear').onchange=e=>{cp().weightYear=e.target.value;saveMeta();renderTopicBreakdown()};
let focusTopic=null;
renderWeakCard=function(){const manual=meta.weakTopics[0];const hardest=MODULES.filter(m=>(difficulty[m.id]||0)>=4).sort((a,b)=>difficulty[b.id]-difficulty[a.id])[0];weak.style.display='block';if(manual){$('weakTitle').textContent=manual;$('weakSub').textContent=`Bạn đã đánh dấu cần ôn · ${topicStats(manual).done}/${topicStats(manual).total} module đã học.`}else if(hardest){$('weakTitle').textContent=hardest.name;$('weakSub').textContent=`Bạn đánh giá độ khó ${difficulty[hardest.id]}/5. Dành một phiên để củng cố phần này.`}else{$('weakTitle').textContent='Ưu tiên phần bạn thấy khó nhất';$('weakSub').textContent='Đánh dấu một topic cần ôn hoặc chấm độ khó 4–5 sao để đặt trọng tâm cho phiên học.'}$('weakGoBtn').textContent=manual||hardest?'Bắt đầu ôn · 25 phút →':'Chọn topic cần ôn →';$('weakGoBtn').onclick=()=>{if(!manual&&!hardest){topics.scrollIntoView({behavior:'smooth'});return}focusTopic=manual||hardest.topic;openFocusMode();pomState={phase:'focus',remaining:1500000,end:Date.now()+1500000};writeLocal('cfa-cp-pomodoro',pomState);updatePomo()}};

// Mock performance uses personal targets. Scores do not establish pass probability.
renderMockExams=function(){const tests=[...mockTests].filter(t=>t.total>0&&t.correct>=0&&t.correct<=t.total).sort((a,b)=>a.date.localeCompare(b.date)),latest=tests.at(-1),goal=cp().mockGoal;$('mockList').innerHTML=[...tests].reverse().map(t=>`<div class="mock-row"><div><div class="mock-name">${esc(t.name)}</div><div class="mock-date">${esc(t.date)}</div></div><div><span class="mock-score">${(t.correct/t.total*100).toFixed(1)}%</span><button class="mock-del" data-delete-mock="${esc(t.id)}" aria-label="Xóa kết quả ${esc(t.name)}">×</button></div></div>`).join('')||'<div class="empty-hint">Chưa có bài thi thử nào.</div>';$('mockList').querySelectorAll('[data-delete-mock]').forEach(b=>b.onclick=()=>confirmAction('Xóa kết quả mock?','Kết quả này sẽ bị xóa khỏi lịch sử.',()=>{deleteMockTest(b.dataset.deleteMock);checkMilestones()}));$('cpMockLatest').textContent=latest?(latest.correct/latest.total*100).toFixed(1)+'%':'—';$('cpMockLatestLabel').textContent=latest?`${latest.name} · ${latest.date}`:'Ghi lại bài thi thử đầu tiên';const pct=latest?latest.correct/latest.total*100:null;$('cpMockBadge').textContent=pct===null?'Chưa có dữ liệu':pct>=goal?'Đạt mục tiêu cá nhân':`Còn ${(goal-pct).toFixed(1)} điểm % tới mục tiêu`;$('cpMockBadge').className='cp-mock-badge '+(pct!==null&&pct>=goal?'good':'');const svg=$('mockTrend');svg.style.display='block';svg.setAttribute('aria-label',tests.length?`Điểm ${tests.length} bài mock: ${tests.map(t=>(t.correct/t.total*100).toFixed(1)+'%').join(', ')}. Mục tiêu ${goal}%.`:'Chưa có điểm mock để hiển thị.');const pts=tests.map((t,i)=>[tests.length===1?150:12+i/(tests.length-1)*276,90-t.correct/t.total*75]);const line=pts.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(1)} ${y.toFixed(1)}`).join(' ');const goalY=90-goal/100*75;svg.innerHTML=`<defs><linearGradient id="cpMockGradient" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#06b6d4" stop-opacity=".18"/><stop offset="1" stop-color="#06b6d4" stop-opacity="0"/></linearGradient></defs><path d="M12 90H288" stroke="#edf0f5"/><path d="M12 ${goalY}H288" stroke="#b4a9f4" stroke-dasharray="4 5"/><text x="285" y="${Math.max(10,goalY-5)}" fill="#9e93ce" font-size="8" text-anchor="end">GOAL ${goal}%</text>${pts.length>1?`<path d="${line}L288 90H12Z" fill="url(#cpMockGradient)"/><path d="${line}" fill="none" stroke="#06b6d4" stroke-width="2.5" stroke-linejoin="round"/>`:''}${pts.map(([x,y])=>`<circle cx="${x}" cy="${y}" r="3.5" fill="#fff" stroke="#06b6d4" stroke-width="2"/>`).join('')}`;if(!latest)svg.innerHTML+='<text x="150" y="78" fill="#abb2c2" text-anchor="middle" font-size="10">Điểm thật. Tiến bộ thật.</text>'};
$('cpMockGoal').onchange=e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<1||n>100){e.target.value=cp().mockGoal;toast('Mục tiêu cần là số nguyên từ 1 đến 100%.');return}cp().mockGoal=n;saveMeta();renderMockExams();renderMetrics()};
const originalAddMock=addMockTest;addMockTest=function(){const n=mockTests.length;originalAddMock();if(mockTests.length>n){checkMilestones();renderMetrics();toast('Đã lưu kết quả mock.')}};window.addMockTest=addMockTest;

// Planner guards and day selection. Existing export and schedule storage are retained.
const originalPlanner=openPlanner;openPlanner=function(day){originalPlanner(day);$('cpPlannerDay').innerHTML=Array.from({length:meta.totalDays},(_,i)=>`<option value="${i+1}" ${i+1===day?'selected':''}>Day ${i+1}</option>`).join('')};window.openPlanner=openPlanner;
renderSchedule=function(){const days=Array.from({length:meta.totalDays},(_,i)=>i+1).filter(d=>modulesForDay(d).length||timeBlocks[d]?.length);$('scheduleList').innerHTML=days.map(d=>`<div class="sched-row"><span class="sched-day">Day ${String(d).padStart(2,'0')}</span><span class="sched-blocks">${(timeBlocks[d]||[]).length?[...timeBlocks[d]].sort((a,b)=>a.start.localeCompare(b.start)).map(b=>`<span class="block-chip">${esc(b.start)}–${esc(b.end)}${b.label?' · '+esc(b.label):''}<button data-del-block="${esc(b.id)}" data-block-day="${d}" aria-label="Xóa khung giờ ${esc(b.start)} ngày ${d}">×</button></span>`).join(''):'<span style="font-size:11px;color:var(--sub)">Chưa đặt khung giờ</span>'}</span><button class="plan-btn" data-plan="${d}">Plan</button></div>`).join('')||'<div class="empty-hint">Thêm khung giờ để bắt đầu lên lịch.</div>';$('scheduleList').querySelectorAll('[data-plan]').forEach(b=>b.onclick=()=>openPlanner(Number(b.dataset.plan)));$('scheduleList').querySelectorAll('[data-del-block]').forEach(b=>b.onclick=()=>deleteBlock(Number(b.dataset.blockDay),b.dataset.delBlock))};
const originalAddBlock=addBlock;addBlock=function(){const start=$('blockStart').value,end=$('blockEnd').value;if(end<=start){toast('Giờ kết thúc cần sau giờ bắt đầu.');return}if((timeBlocks[plannerDay]||[]).some(b=>start<b.end&&end>b.start)){toast('Khung giờ bị trùng với một buổi đã đặt trong ngày này.');return}originalAddBlock();toast('Đã thêm khung giờ học.')};window.addBlock=addBlock;

// A real 90-day, local-calendar contribution history (no UTC day shift).
renderHeatmap=function(){const today=new Date();today.setHours(0,0,0,0);const start=new Date(today);start.setDate(start.getDate()-89);const leading=start.getDay();let html=Array.from({length:leading},()=>'<span class="hcell" style="visibility:hidden"></span>').join('');let active=0,total=0;for(let i=0;i<90;i++){const date=new Date(start);date.setDate(date.getDate()+i);const key=localDay(date),count=studyLog[key]||0,mins=timeLog[key]||0;const level=count>=5?4:count>=3?3:count>=1?2:mins>0?1:0;if(count||mins)active++;total+=count;html+=`<div class="hcell ${level?'l'+level:''}" title="${key}: ${count} module · ${fmtHM(mins)}" role="img" aria-label="${key}: ${count} module, ${fmtHM(mins)}"></div>`}$('heatmapGrid').innerHTML=html;$('cpHeatStats').innerHTML=`<span><strong>${active}</strong>ngày học / 90 ngày</span><span><strong>${total}</strong>lượt hoàn thành</span><span><strong>${displayedStreak()}</strong>ngày liên tiếp</span>`};

// Spaced review: successive intervals of 1, 3, 7, 14 and 30 days.
const intervals=[1,3,7,14,30];
function reviewDue(m){const history=cp().reviewDates[m.id]||[];const last=history.at(-1)||cp().completedAt[m.id];if(!last)return localDay();const d=new Date(last);d.setDate(d.getDate()+intervals[Math.min(history.length,intervals.length-1)]);return localDay(d)}
renderWeeklyReview=function(){const done=MODULES.filter(m=>progress[m.id]);const due=done.filter(m=>reviewDue(m)<=localDay());$('cpReviewSummary').textContent=done.length?`${due.length} module đến hạn · nhịp ôn 1, 3, 7, 14, 30 ngày`:'Hoàn thành module đầu tiên để bắt đầu lịch ôn cách quãng.';const weeks={};done.forEach(m=>(weeks[Math.floor((effectiveDay(m)-1)/7)]??=[]).push(m));$('weeklyReview').innerHTML=Object.entries(weeks).map(([w,mods])=>`<div class="week-card"><div class="week-head" data-week="${w}" role="button" tabindex="0" aria-expanded="${openWeeks.has(Number(w))}"><div><div class="week-title">Tuần ${Number(w)+1} · Day ${Number(w)*7+1}–${Math.min(meta.totalDays,(Number(w)+1)*7)}</div><div class="week-sub">${mods.length} đã học · ${mods.filter(m=>reviewDue(m)<=localDay()).length} đến hạn ôn</div></div><span class="review-pct" style="background:var(--blue-soft);color:var(--blue)">${mods.filter(m=>(cp().reviewDates[m.id]||[]).length>0||reviewed[m.id]).length}/${mods.length}</span></div><div class="week-body ${openWeeks.has(Number(w))?'open':''}">${mods.map(m=>{const reviewedToday=(cp().reviewDates[m.id]||[]).at(-1);const checked=!!reviewedToday&&localDay(reviewedToday)===localDay();return `<div class="review-row ${checked?'reviewed':''}"><button class="chk ${checked?'checked':''}" data-review="${m.id}" role="checkbox" aria-checked="${checked}" aria-label="Đã ôn ${esc(m.name)} hôm nay">${checked?'✓':''}</button><span class="rname">${esc(m.name)}<br><span class="cp-review-date">${checked?'Đã ôn hôm nay':reviewDue(m)<=localDay()?'Đến hạn ôn':'Ôn tiếp: '+reviewDue(m)}</span></span></div>`}).join('')}</div></div>`).join('');$('weeklyReview').querySelectorAll('[data-week]').forEach(b=>b.onclick=()=>toggleWeekOpen(Number(b.dataset.week)));$('weeklyReview').querySelectorAll('[data-review]').forEach(b=>b.onclick=()=>{const id=b.dataset.review,history=cp().reviewDates[id]??=[];if(history.length&&localDay(history.at(-1))===localDay())history.pop();else history.push(new Date().toISOString());reviewed[id]=history.length>0;saveReviewed();saveMeta();renderWeeklyReview();renderMetrics()})};

// Video timestamp notes are nested in meta, so the existing sync payload includes them.
let activeVideo=null;
const originalOpenVideo=window.openVideoModal;
window.openVideoModal=function(id){activeVideo=id;originalOpenVideo(id);if(videoLinks[id]&&extractYoutubeId(videoLinks[id]))renderVideoNotes(id)};
function renderVideoNotes(id){$('vmBody').querySelector('.cp-notes')?.remove();const section=el('section','cp-notes','<h4>Ghi chú theo mốc thời gian</h4><form class="cp-note-form" id="cpVideoNoteForm"><input id="cpNoteTime" placeholder="02:30" aria-label="Mốc thời gian, phút:giây" pattern="[0-9]+:[0-5][0-9]" required><input id="cpNoteText" maxlength="2000" placeholder="Ý chính cần nhớ…" aria-label="Nội dung ghi chú" required><button class="btn" type="submit">Lưu</button></form><div id="cpNoteError" class="cp-form-error" role="alert"></div><div id="cpVideoNotesList"></div>');$('vmBody').append(section);const notes=cp().videoNotes[id]||[];$('cpVideoNotesList').innerHTML=[...notes].sort((a,b)=>a.seconds-b.seconds).map(n=>`<div class="cp-video-note"><button class="stamp" data-seek="${Number(n.seconds)}">${String(Math.floor(n.seconds/60)).padStart(2,'0')}:${String(n.seconds%60).padStart(2,'0')}</button><span>${esc(n.text)}</span><button class="delete-note" data-delete-note="${esc(n.id)}" aria-label="Xóa ghi chú">×</button></div>`).join('');$('cpVideoNoteForm').onsubmit=e=>{e.preventDefault();const raw=$('cpNoteTime').value.trim(),text=$('cpNoteText').value.trim();if(!/^\d+:[0-5]\d$/.test(raw)||!text){$('cpNoteError').textContent='Nhập mốc phút:giây và nội dung ghi chú.';return}const [minutes,seconds]=raw.split(':').map(Number);if(minutes>9999){$('cpNoteError').textContent='Mốc thời gian quá lớn.';return}(cp().videoNotes[id]??=[]).push({id:uid(),seconds:minutes*60+seconds,text});saveMeta();renderVideoNotes(id);toast('Đã lưu ghi chú video.')};section.querySelectorAll('[data-seek]').forEach(b=>b.onclick=()=>{$('vmBody').querySelector('iframe').src=`https://www.youtube-nocookie.com/embed/${extractYoutubeId(videoLinks[id])}?start=${Number(b.dataset.seek)}&autoplay=1`});section.querySelectorAll('[data-delete-note]').forEach(b=>b.onclick=()=>{cp().videoNotes[id]=notes.filter(n=>n.id!==b.dataset.deleteNote);saveMeta();renderVideoNotes(id)})}

// Safe micro-Markdown: text stays escaped before adding limited formatting.
function markdown(s){const format=line=>esc(line).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*([^*]+)\*/g,'<em>$1</em>').replace(/`([^`]+)`/g,'<code>$1</code>');return s.split('\n').map(line=>line.startsWith('# ')?'<h3>'+format(line.slice(2))+'</h3>':line.startsWith('- ')?'<ul><li>'+format(line.slice(2))+'</li></ul>':'<p>'+format(line||' ')+'</p>').join('')}
$('cpJournalPreview').onclick=()=>{const show=preview.hidden;preview.hidden=!show;$('journalInput').hidden=show;preview.innerHTML=markdown($('journalInput').value)||'<p>Chưa có ghi chú hôm nay.</p>';$('cpJournalPreview').textContent=show?'Tiếp tục viết':'Xem trước'};
let cpJournalTimer;$('journalInput').addEventListener('input',()=>{journal[localDay()]=$('journalInput').value;$('cpJournalStatus').textContent='Đang lưu…';clearTimeout(cpJournalTimer);cpJournalTimer=setTimeout(()=>{let saved=false;try{saved=JSON.parse(localStorage.getItem('cfa-journal')||'{}')[localDay()]===journal[localDay()]}catch{}$('cpJournalStatus').textContent=saved?'Đã lưu trên thiết bị · hỗ trợ **đậm**, *nghiêng*, danh sách':'Chưa lưu được trên thiết bị'},850)});
addEventListener('pagehide',()=>{clearTimeout(journalTimer);journal[localDay()]=$('journalInput').value;try{localStorage.setItem('cfa-journal',JSON.stringify(journal))}catch{}});

// Focus checklist and a separate Pomodoro clock.
openFocusMode=function(){const day=Math.min(currentProgramDay(),meta.totalDays),mods=focusTopic?MODULES.filter(m=>m.topic===focusTopic):modulesForDay(day);$('focusTitle').textContent=focusTopic?`Ôn tập · ${focusTopic}`:`Hôm nay · Day ${day}`;$('focusList').innerHTML=mods.map(m=>`<div class="module-row ${progress[m.id]?'done':''}" draggable="false"><button class="chk ${progress[m.id]?'checked':''}" data-focus-complete="${m.id}" role="checkbox" aria-checked="${!!progress[m.id]}" aria-label="Hoàn thành ${esc(m.name)}">${progress[m.id]?'✓':''}</button><div class="mname">${esc(m.name)}</div></div>`).join('')||'<div class="empty-hint" style="padding:24px">Chưa có module cho ngày này. Bạn có thể xếp lịch trong Study Planner.</div>';$('focusList').querySelectorAll('[data-focus-complete]').forEach(b=>b.onclick=()=>{const id=b.dataset.focusComplete;toggleModule(id);openFocusMode();$('focusList').querySelector(`[data-focus-complete="${id}"]`)?.focus()});$('focusOverlay').classList.add('open');updatePomo()};
window.refreshFocus=()=>openFocusMode();$('cpFocusTop').onclick=()=>{focusTopic=null;openFocusMode()};$('focusBtn').onclick=()=>{focusTopic=null;openFocusMode()};
const openSettings=()=>{settings.open=true;settings.scrollIntoView({behavior:'smooth'})};$('cpSyncTop').onclick=()=>{openSettings();setTimeout(()=>$('syncCodeInput').focus(),250)};$('cpProfileTop').onclick=()=>{openSettings();setTimeout(()=>$('cpCandidateName').focus(),250)};
$('cpCandidateName').onchange=e=>{cp().candidate=e.target.value.trim()||'Candidate';saveMeta();renderMetrics()};

// Sync status is only reported as current after a successful response.
let lastSynced=null,currentSync='off',syncReady=!SYNC_CODE;
const previousSyncStatus=setSyncStatus;setSyncStatus=function(state){previousSyncStatus(state);currentSync=state;if(state==='on'&&SYNC_CODE){lastSynced=Date.now();syncReady=true}syncStatusTick()};
function syncStatusTick(){
 const n=$('cpSyncLabel'),dot=$('cpSyncDot');if(!n)return;
 // This live label owns its translation. A generic translator must not rewrite it.
 n.setAttribute('translate','no');
 const en=document.body.dataset.language==='en';
 const state=!SYNC_CODE?'local':currentSync==='syncing'?'syncing':currentSync==='error'?'error':lastSynced?'on':'waiting';
 const labels=en?{local:'Saved on this device',syncing:'Syncing…',error:'Sync failed · check connection',on:'Synced',waiting:'Waiting for sync'}:{local:'Lưu trên thiết bị',syncing:'Đang đồng bộ…',error:'Chưa đồng bộ · kiểm tra kết nối',on:'Đã đồng bộ',waiting:'Chờ xác nhận đồng bộ'};
 if(n.textContent!==labels[state])n.textContent=labels[state];
 if(n.dataset.syncState!==state)n.dataset.syncState=state;
 dot?.classList.toggle('on',state==='on');
}
window.CharterSyncStatus={render:syncStatusTick};

// A failed pull must never be treated as an empty remote record and overwrite it.
let pulling=false,syncGeneration=0;
queueSync=function(){if(!SYNC_CODE||pulling||!syncReady)return;clearTimeout(syncTimer);syncTimer=setTimeout(()=>supabasePush(),900)};
const payload=()=>({progress,studyLog,meta,dayOverride,timeBlocks,reviewed,timeLog,mockTests,difficulty,journal,sessions,milestones,videoLinks});
supabasePush=async function(){if(!SYNC_CODE||pulling||!syncReady)return;const code=SYNC_CODE,generation=syncGeneration;setSyncStatus('syncing');try{const res=await fetch(`${SUPABASE_URL}/rest/v1/sync_data`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`,'Content-Type':'application/json',Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:code,data:payload(),updated_at:new Date().toISOString()}),signal:AbortSignal.timeout(12000)});if(!res.ok)throw Error('sync failed');if(generation===syncGeneration)setSyncStatus('on')}catch{if(generation===syncGeneration){setSyncStatus('error');$('syncStatus').textContent='Chưa đồng bộ · sẽ thử lại khi có thay đổi'}}};
supabasePull=async function(){if(!SYNC_CODE)return false;const code=SYNC_CODE,generation=syncGeneration;pulling=true;setSyncStatus('syncing');try{const res=await fetch(`${SUPABASE_URL}/rest/v1/sync_data?id=eq.${encodeURIComponent(code)}&select=data,updated_at`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${SUPABASE_ANON_KEY}`},signal:AbortSignal.timeout(12000)});if(!res.ok)throw Error('pull failed');const rows=await res.json();if(generation!==syncGeneration)return null;if(!Array.isArray(rows))throw Error('invalid response');if(!rows.length){setSyncStatus('on');return false}const data=rows[0].data;if(!data||typeof data!=='object'||Array.isArray(data))throw Error('invalid record');for(const key of ['progress','studyLog','meta','dayOverride','timeBlocks','reviewed','timeLog','difficulty','journal','milestones','videoLinks'])if(data[key]!==undefined&&(!data[key]||typeof data[key]!=='object'||Array.isArray(data[key])))throw Error('invalid '+key);for(const key of ['mockTests','sessions'])if(data[key]!==undefined&&!Array.isArray(data[key]))throw Error('invalid '+key);if(data.meta?.totalDays&&(!Number.isInteger(data.meta.totalDays)||data.meta.totalDays<25||data.meta.totalDays>365))throw Error('invalid duration');progress=data.progress||{};studyLog=data.studyLog||{};meta={...meta,...(data.meta||{})};dayOverride=data.dayOverride||{};timeBlocks=data.timeBlocks||{};reviewed=data.reviewed||{};timeLog=data.timeLog||{};mockTests=data.mockTests||[];difficulty=data.difficulty||{};journal=data.journal||{};sessions=data.sessions||[];milestones=data.milestones||{};videoLinks=data.videoLinks||{};saveProgress();saveStudyLog();saveMeta();saveSchedule();saveReviewed();saveTimeLog();saveMockTests();saveDifficulty();saveJournal();saveSessions();saveMilestones();saveVideoLinks();setSyncStatus('on');return true}catch{if(generation===syncGeneration)setSyncStatus('error');return null}finally{if(generation===syncGeneration)pulling=false}};
const oldSyncInput=$('syncCodeInput'),syncInput=oldSyncInput.cloneNode(true);oldSyncInput.replaceWith(syncInput);syncInput.addEventListener('change',async()=>{clearTimeout(syncTimer);syncGeneration++;syncReady=false;SYNC_CODE=syncInput.value.trim();try{localStorage.setItem('cfa-sync-code',SYNC_CODE)}catch{}lastSynced=null;if(!SYNC_CODE){pulling=false;setSyncStatus('off');return}const result=await supabasePull();if(result===true){render();toast('Đã tải dữ liệu đồng bộ.')}else if(result===false)queueSync();else toast('Chưa kết nối được. Dữ liệu trên thiết bị vẫn được giữ.')});
addEventListener('online',()=>{if(SYNC_CODE&&currentSync==='error')queueSync()});

const oldRender=render;render=function(){oldRender();renderMetrics();renderGoldenHour();$('totalDaysHint').textContent=`${meta.totalDays} ngày · ${TOTAL} module. Số ngày có thể đổi trong khoảng 25–90; tên module luôn được giữ nguyên.`;renderWeeklyReview();updateTimerDisplay()};
function tick(){updateTimerDisplay();updatePomo();$('cpLiveStreak').textContent=`${displayedStreak()} DAY`;if(meta.examDate){const delta=new Date(meta.examDate+'T00:00:00').getTime()-Date.now();$('cpLiveCountdown').textContent=delta<0?'Đã tới ngày thi':`${Math.floor(delta/86400000)}d ${String(Math.floor(delta/3600000)%24).padStart(2,'0')}h ${String(Math.floor(delta/60000)%60).padStart(2,'0')}m`}else $('cpLiveCountdown').textContent='Chưa đặt'}
sidebar.querySelectorAll('a').forEach(a=>a.onclick=()=>{sidebar.querySelectorAll('a').forEach(n=>n.classList.remove('active'));a.classList.add('active')});const navObserver=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){sidebar.querySelectorAll('a').forEach(a=>{a.classList.toggle('active',a.hash==='#'+e.target.id);if(a.hash==='#'+e.target.id)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current')})}})},{rootMargin:'-10% 0px -65% 0px'});['roadmap','modules','schedule','mocks','analytics','review'].forEach(id=>navObserver.observe($(id)));
// Original keyboard helper handles legacy div controls. Native buttons already
// activate themselves; stop the helper from clicking them a second time.
document.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('button.chk,button.star'))e.stopImmediatePropagation()},true);
render();syncStatusTick();tick();setInterval(tick,1000);
// Small internal test surface; no dependencies or network calls are needed.
window.CharterPrep={localDay,dayNumber,neededMetrics,markdown,sessionMs,reviewDue,getSession:()=>JSON.parse(JSON.stringify(session)),getPomo:()=>({...pomState})};
})();
