(()=>{
'use strict';
const $=id=>document.getElementById(id);
function metrics(){
 const date=CharterPrep.localDay(),plan=meta.charterPrep?.dailyModulePlan,hasPlan=plan?.date===date&&plan.ids?.length>0,items=hasPlan?MODULES.filter(m=>plan.ids.includes(m.id)):[],completed=hasPlan?items.filter(m=>progress[m.id]).length:MODULES.filter(m=>progress[m.id]&&meta.charterPrep?.completedAt?.[m.id]&&CharterPrep.localDay(meta.charterPrep.completedAt[m.id])===date).length,remaining=MODULES.filter(m=>!progress[m.id]).length,base=remaining+completed,available=CharterPrep.neededMetrics().available,recommended=base?Math.ceil(base/available):0,setting=meta.charterPrep?.dailyModuleGoal,manual=setting?.date===date&&Number.isInteger(setting.target)&&setting.target>=0&&setting.target<=1000,target=manual?setting.target:hasPlan?items.length:recommended;
 return{date,completed,remaining,base,available,recommended,target,manual,hasPlan,shortfall:Math.max(0,target-completed),total:MODULES.length,programCompleted:MODULES.length-remaining};
}
const card=document.createElement('section');card.className='daily-goal-card';card.id='dailyModuleGoal';card.setAttribute('aria-labelledby','dailyGoalTitle');card.innerHTML='<div class="daily-goal-heading"><div><span class="daily-goal-label" id="dailyGoalMode"></span><h2 id="dailyGoalTitle">Mục tiêu hôm nay</h2></div><div class="daily-goal-actions"><button class="btn ghost" id="dailyPlanEdit">Chọn module hôm nay</button><button class="btn ghost" id="dailyGoalEdit">Điều chỉnh</button></div></div><div class="daily-goal-main"><div><strong id="dailyGoalNumber"></strong><span> module</span><p id="dailyGoalStatus" role="status"></p></div><button class="btn" id="dailyGoalNext">Học module tiếp theo →</button></div><div class="daily-goal-track" id="dailyGoalProgress" role="progressbar" aria-label="Tiến độ mục tiêu module hôm nay" aria-valuemin="0" aria-valuemax="100"><i id="dailyGoalFill"></i></div><p class="daily-goal-note" id="dailyGoalReason"></p><div class="daily-plan-summary" id="dailyPlanSummary"></div>';$('ux-page-today').querySelector('.studio-stats').after(card);
const dialog=document.createElement('dialog');dialog.className='lab-dialog';dialog.id='dailyGoalDialog';dialog.setAttribute('aria-labelledby','dailyGoalDialogTitle');dialog.innerHTML='<div class="lab-dialog-head"><h2 id="dailyGoalDialogTitle">Mục tiêu module hôm nay</h2><button class="lab-dialog-close" id="dailyGoalClose" aria-label="Đóng">×</button></div><div class="lab-dialog-body"><form id="dailyGoalForm" class="lab-form"><label class="wide">Số module muốn hoàn thành<input id="dailyGoalInput" type="number" min="0" max="1000" step="1" required></label><p class="wide" id="dailyGoalSuggestion"></p><p class="wide">Điều chỉnh chỉ áp dụng cho hôm nay. Nhập 0 nếu muốn nghỉ học module; ngày mai web tự tính lại.</p><p class="lab-form-error wide" id="dailyGoalError" role="alert"></p><div class="lab-form-actions"><button type="button" class="btn ghost" id="dailyGoalAuto">Dùng mục tiêu tự động</button><button type="submit" class="btn">Lưu hôm nay</button></div></form></div>';document.body.append(dialog);
const planDialog=document.createElement('dialog');planDialog.className='lab-dialog';planDialog.id='dailyPlanDialog';planDialog.innerHTML='<div class="lab-dialog-head"><h2>Module học hôm nay</h2><button class="lab-dialog-close" id="dailyPlanClose" aria-label="Đóng">×</button></div><div class="lab-dialog-body"><form id="dailyPlanForm" class="lab-form"><label class="wide daily-plan-select-label">Chọn các module muốn học hôm nay<small>Giữ Ctrl/Cmd để chọn nhiều. Để trống để dùng gợi ý tự động.</small><select id="dailyPlanModules" multiple size="9"></select></label><p class="wide" id="dailyPlanError" role="alert"></p><div class="lab-form-actions"><button type="button" class="btn ghost" id="dailyPlanAuto">Xoá lựa chọn, dùng tự động</button><button type="submit" class="btn">Lưu kế hoạch</button></div></form></div>';document.body.append(planDialog);
function planned(){const p=meta.charterPrep?.dailyModulePlan;return p?.date===CharterPrep.localDay()?MODULES.filter(m=>p.ids?.includes(m.id)):[]}
function drawPlan(){const p=planned(),open=p.filter(m=>!progress[m.id]);$('dailyPlanSummary').innerHTML=p.length?`<div class="daily-plan-heading"><strong>Todo hôm nay · ${p.length} module</strong><span>${open.length?`${open.length} còn lại`:'Đã hoàn thành'}</span></div><div class="daily-plan-list">${p.map(m=>`<button type="button" class="daily-plan-item${progress[m.id]?' is-done':''}" data-plan-module="${escapeHtml(m.id)}" aria-pressed="${progress[m.id]?'true':'false'}" aria-label="${progress[m.id]?'Bỏ hoàn thành':'Đánh dấu hoàn thành'} ${escapeHtml(m.name)}"><i>${progress[m.id]?'✓':'○'}</i><span>${escapeHtml(m.name)}<small>${escapeHtml(m.topic)} · Ngày ${effectiveDay(m)}</small></span></button>`).join('')}</div>`:'<div class="daily-plan-empty">Hôm nay chưa chọn bài riêng · web sẽ tự đề xuất theo lộ trình</div>';$('dailyPlanSummary').querySelectorAll('[data-plan-module]').forEach(btn=>btn.onclick=()=>toggleModule(btn.dataset.planModule));}
function openPlan(){const chosen=new Set(planned().map(m=>m.id));$('dailyPlanModules').innerHTML=MODULES.filter(m=>!progress[m.id]).sort((a,b)=>effectiveDay(a)-effectiveDay(b)).map(m=>`<option value="${escapeHtml(m.id)}"${chosen.has(m.id)?' selected':''}>${escapeHtml(m.name)} · ${escapeHtml(m.topic)} · Ngày ${effectiveDay(m)}</option>`).join('');$('dailyPlanError').textContent='';planDialog.showModal()}
function draw(){const m=metrics(),pct=m.target?Math.min(100,m.completed/m.target*100):0;$('dailyGoalMode').textContent=m.manual?'BẠN ĐẶT CHO HÔM NAY':'TỰ ĐỘNG THEO LỘ TRÌNH';$('dailyGoalNumber').textContent=m.shortfall;$('dailyGoalStatus').textContent=!m.base?'Chưa có module cần học.':!m.target?'Hôm nay nghỉ học module.':m.shortfall?`Đã học ${m.completed} · Còn ${m.shortfall} module để đạt mục tiêu`:`Đã học ${m.completed} · Đạt mục tiêu hôm nay!`;$('dailyGoalFill').style.width=pct+'%';$('dailyGoalProgress').setAttribute('aria-valuenow',String(Math.round(pct)));$('dailyGoalProgress').setAttribute('aria-valuetext',`${m.completed} / ${m.target} module`);card.classList.toggle('goal-achieved',m.target>0&&!m.shortfall);$('dailyGoalReason').textContent=m.manual?`Mục tiêu riêng hôm nay. Gợi ý tự động: ${m.recommended} module. Ngày mai sẽ tính lại.`:`${m.base} module chưa hoàn thành trước khi tính các bài đã học hôm nay ÷ ${m.available} ngày còn lại, làm tròn lên.${!meta.programStart?' Chưa đặt ngày bắt đầu: tạm tính theo độ dài lộ trình hiện tại.':''} Chỉ tính bài được đánh dấu hoàn thành hôm nay; ôn lại không cộng thêm.`;$('dailyGoalNext').hidden=!m.remaining;$('dailyGoalNext').textContent=m.shortfall?'Học module tiếp theo →':'Tiếp tục học →';drawPlan()}
function save(target){meta.charterPrep??={};const before=meta.charterPrep.dailyModuleGoal;if(target===null)delete meta.charterPrep.dailyModuleGoal;else meta.charterPrep.dailyModuleGoal={date:CharterPrep.localDay(),target};try{localStorage.setItem('cfa-meta',JSON.stringify(meta))}catch{if(before===undefined)delete meta.charterPrep.dailyModuleGoal;else meta.charterPrep.dailyModuleGoal=before;$('dailyGoalError').textContent='Chưa lưu được mục tiêu trên thiết bị. Hãy thử lại.';return false}saveMeta();draw();return true}
$('dailyGoalEdit').onclick=()=>{const m=metrics();$('dailyGoalInput').value=m.target;$('dailyGoalSuggestion').textContent=`Web gợi ý ${m.recommended} module. Hôm nay đã hoàn thành ${m.completed}; còn ${m.remaining} bài chưa hoàn thành trong chương trình.`;$('dailyGoalError').textContent='';dialog.showModal();$('dailyGoalInput').focus()};$('dailyGoalClose').onclick=()=>dialog.close();$('dailyGoalForm').onsubmit=e=>{e.preventDefault();const target=Number($('dailyGoalInput').value),m=metrics();if($('dailyGoalInput').value===''||!Number.isInteger(target)||target<0||target>Math.min(1000,m.base)){$('dailyGoalError').textContent=`Nhập số nguyên từ 0 đến ${Math.min(1000,m.base)} module.`;return}if(save(target))dialog.close()};$('dailyGoalAuto').onclick=()=>{if(save(null))dialog.close()};$('dailyGoalNext').onclick=()=>{const next=MODULES.filter(m=>!progress[m.id]).sort((a,b)=>effectiveDay(a)-effectiveDay(b))[0];if(next)CharterExperience.openModule(next.id)};
// The dashboard plan is date-scoped, so changing it never alters the curriculum or completion data.
$('dailyPlanEdit').onclick=openPlan;$('dailyPlanClose').onclick=()=>planDialog.close();$('dailyPlanAuto').onclick=()=>{const select=$('dailyPlanModules');for(const option of select.options)option.selected=false;select.dispatchEvent(new Event('change',{bubbles:true}))};$('dailyPlanForm').onsubmit=e=>{e.preventDefault();const ids=[...$('dailyPlanModules').selectedOptions].map(o=>o.value);meta.charterPrep??={};meta.charterPrep.dailyModulePlan={date:CharterPrep.localDay(),ids};localStorage.setItem('cfa-meta',JSON.stringify(meta));saveMeta();draw();planDialog.close()};
const previous=render;render=function(){previous();draw()};let day=CharterPrep.localDay();const checkDay=()=>{const today=CharterPrep.localDay();if(today!==day){day=today;draw()}};setInterval(checkDay,30000);addEventListener('focus',checkDay);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkDay()});draw();window.DailyModuleGoal={metrics,draw};
// Prefer the explicitly selected dashboard plan when opening the next lesson.
$('dailyGoalNext').onclick=()=>{const next=planned().find(m=>!progress[m.id])||MODULES.filter(m=>!progress[m.id]).sort((a,b)=>effectiveDay(a)-effectiveDay(b))[0];if(next)CharterExperience.openModule(next.id)};
const dailyDateLabel=document.createElement('span');dailyDateLabel.className='daily-goal-date';dailyDateLabel.id='dailyGoalDate';dailyDateLabel.textContent='';card.querySelector('#dailyGoalTitle').before(dailyDateLabel);
const previousDailyDraw=draw;draw=function(){previousDailyDraw();const date=metrics().date;dailyDateLabel.textContent=new Intl.DateTimeFormat('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(date+'T12:00:00'))};draw();

const program=document.createElement('section');program.className='program-overview';program.innerHTML='<span class="daily-goal-label">CẢ CHƯƠNG TRÌNH</span><h3>Tiến độ tổng thể</h3><div><strong id="programRemaining"></strong><span> module còn lại</span></div><p id="programStatus"></p><progress id="programProgress" aria-label="Tiến độ cả chương trình"></progress>';
const todayOverview=document.createElement('div');todayOverview.className='today-overview';const main=card.querySelector('.daily-goal-main');main.before(todayOverview);todayOverview.append(main,program);
const status=document.createElement('p');status.id='dailyCompletionCheck';status.setAttribute('role','status');$('dailyPlanSummary').before(status);
let goalSignature='';const originalDraw=draw;draw=function(){originalDraw();const m=metrics();$('dailyGoalMode').textContent=m.manual?'MỤC TIÊU BẠN ĐẶT':m.hasPlan?'THEO TODO HÔM NAY':'GỢI Ý THEO LỘ TRÌNH';$('dailyGoalStatus').textContent=!m.target?'Hôm nay nghỉ học module.':(!m.shortfall?'Đạt mục tiêu hôm nay · ':'')+'Đã học '+m.completed+' / '+m.target+' module hôm nay';$('dailyGoalNumber').nextElementSibling.textContent=' module còn lại hôm nay';$('dailyGoalReason').textContent=m.hasPlan?'Mục tiêu ngày dựa trên danh sách Todo bên dưới.':m.manual?'Mục tiêu riêng hôm nay. Bạn có thể điều chỉnh bất kỳ lúc nào.':'Chưa chọn Todo: đây là mức gợi ý theo thời gian còn lại. Chọn bài hoặc điều chỉnh mục tiêu phù hợp với bạn.';$('programRemaining').textContent=m.remaining;$('programStatus').textContent='Đã hoàn thành '+m.programCompleted+' / '+m.total+' module trong chương trình';$('programProgress').max=m.total||1;$('programProgress').value=m.programCompleted;status.textContent=!m.target?'Hôm nay là ngày nghỉ.':m.shortfall?'Hôm nay đã học xong chưa? Còn '+m.shortfall+' module để đạt mục tiêu ngày.':'Bạn đã hoàn thành mục tiêu hôm nay ✓';status.classList.toggle('is-complete',!m.shortfall);const signature=JSON.stringify(m);if(signature!==goalSignature){goalSignature=signature;window.dispatchEvent(new Event('charter-goal-change'))}};window.DailyModuleGoal.draw=draw;draw();
})();
