/* CharterPrep experience: local navigation, quick search and contextual study tools. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),root=$('appRoot'),header=root.querySelector('.header'),sidebar=root.querySelector('.sidebar');
const esc=s=>escapeHtml(String(s??'')),node=(tag,cls,html='')=>{const n=document.createElement(tag);n.className=cls;n.innerHTML=html;return n};
const icons={today:'M3 10l9-7 9 7M5 9v12h5v-7h4v7h5V9',modules:'M4 4h7a3 3 0 0 1 3 3v14a4 4 0 0 0-4-2H4zM14 7a3 3 0 0 1 3-3h4v15h-3a4 4 0 0 0-4 2',practice:'M9 4h6M9 3v3h6V3M7 4H4v17h16V4h-3M8 11l2 2 5-5M8 17h8',cards:'M4 6l12-3 4 15-12 3zM4 10H2v11h11',roadmap:'M5 3v18M5 4h14l-3 4 3 4H5',schedule:'M4 5h16v16H4zM8 3v4M16 3v4M4 10h16M8 14h2M14 14h2',review:'M3 11a9 9 0 1 1 2 7M3 4v7h7',mocks:'M6 3h12v18H6zM9 8h6M9 12h6M9 16h4',analytics:'M3 3v18h18M7 16v-5M12 16V7M17 16V4',journal:'M5 3h10l4 4v14H5zM9 11h6M9 15h6',settings:'M4 7h16M4 17h16M8 4v6M16 14v6',search:'M20 20l-5-5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',more:'M5 12h1M11 12h1M17 12h1'};
const icon=id=>`<svg class="cp-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[id]||icons.modules}"/></svg>`;
const routes=[['today','Hôm nay','Một bước nhỏ. Gần hơn mỗi ngày.','Tập trung vào những việc quan trọng nhất trong phiên học này.'],['modules','Module học','Không gian học tập','Tìm bài, theo dõi tiến độ và mở mọi công cụ từ một module.'],['practice','Luyện tập','Hiểu sâu qua từng câu hỏi','Ghi kết quả QBank, nhận diện điểm yếu và học lại từ câu sai.'],['cards','Thẻ nhớ','Nhớ lâu, hiểu đúng','Ôn chủ động các công thức và kiến thức bạn đã tự ghi lại.'],['roadmap','Lộ trình','Nhìn rõ hành trình phía trước','Phân bổ module theo ngày và điều chỉnh kế hoạch theo nhịp của bạn.'],['schedule','Lịch học','Dành thời gian cho điều quan trọng','Tổ chức từng phiên học bằng các khung giờ cụ thể.'],['review','Ôn cách quãng','Ôn đúng lúc, nhớ lâu hơn','Theo dõi các module đến hạn và đánh dấu sau khi thực sự ôn lại.'],['mocks','Thi thử','Biết mình đang ở đâu','Theo dõi kết quả thi thử và khoảng cách tới mục tiêu cá nhân.'],['analytics','Thống kê','Mỗi nỗ lực đều có ý nghĩa','Nhìn lại thời gian đã học và những cột mốc bạn đạt được.'],['journal','Nhật ký','Biến trải nghiệm thành bài học','Ghi lại điều đã hiểu, điều còn vướng và bước tiếp theo.'],['settings','Cài đặt','Một không gian của riêng bạn','Cá nhân hóa giao diện, ngày thi và quản lý dữ liệu học.']];
const routeMap=new Map(routes.map(r=>[r[0],r]));let current='',filter='all',sheetId=null;const positions={};
let prefs;try{prefs=JSON.parse(localStorage.getItem('cfa-ux-preferences'))||{}}catch{prefs={}}
if(!['light','dark','system'].includes(prefs.theme))prefs.theme='light';if(!['comfortable','compact'].includes(prefs.density))prefs.density='comfortable';
prefs.recent=Array.isArray(prefs.recent)?[...new Set(prefs.recent)].filter(id=>MODULES.some(m=>m.id===id)).slice(0,5):[];
const media=window.matchMedia?.('(prefers-color-scheme: dark)');
function applyPrefs(){document.body.classList.toggle('ux-dark',prefs.theme==='dark'||prefs.theme==='system'&&!!media?.matches);document.body.classList.toggle('ux-compact',prefs.density==='compact');document.querySelectorAll('[data-ux-theme]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.uxTheme===prefs.theme)));document.querySelectorAll('[data-ux-density]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.uxDensity===prefs.density)))}
function savePrefs(){try{localStorage.setItem('cfa-ux-preferences',JSON.stringify(prefs))}catch{}applyPrefs()}
media?.addEventListener?.('change',applyPrefs);
const cards={ring:$('ringPct').closest('.card'),timer:$('timerBtn').closest('.card'),mock:$('mockList').closest('.card'),roadmap:$('grid25').closest('.card'),topics:$('topicBreakdown').closest('.card'),modules:$('moduleGroups').closest('.card'),milestones:$('milestoneGrid').closest('.card'),heatmap:$('heatmapGrid').closest('.card'),schedule:$('scheduleList').closest('.card'),journal:$('journalInput').closest('.card'),review:$('weeklyReview').closest('.card')};
const pages={};for(const [id,label]of routes){const page=node('section','ux-page');page.id='ux-page-'+id;page.hidden=true;page.setAttribute('aria-label',label);pages[id]=page;root.append(page)}
const move=(id,...nodes)=>nodes.filter(Boolean).forEach(n=>pages[id].append(n));
const overview=node('div','ux-overview-lower');overview.append(cards.ring,cards.timer,$('weakCard'));move('today',root.querySelector('.goal'),$('today'),root.querySelector('.cp-stats'),overview);
const resume=node('section','px-resume');resume.id='pxResume';resume.setAttribute('aria-label','Quay lại bài học');$('today').before(resume);
function renderResume(){const recent=MODULES.find(m=>m.id===prefs.recent[0]),m=recent||[...MODULES].filter(m=>!progress[m.id]).sort((a,b)=>effectiveDay(a)-effectiveDay(b))[0];if(!m){resume.hidden=true;return}resume.hidden=false;const q=StudyLab.qStats(m.id);resume.innerHTML=`<div class="px-resume-mark">${icon('modules')}</div><div class="px-resume-content"><span class="px-label">${recent?'BÀI VỪA MỞ':'BẮT ĐẦU TỪ MODULE NÀY'}</span><h2>${esc(m.name)}</h2><p>${esc(m.topic)} <span>·</span> Ngày ${effectiveDay(m)} <span>·</span> ${progress[m.id]?'Đã hoàn thành':'Chưa hoàn thành'}${q.total?' · QBank '+Math.round(q.accuracy*100)+'%':''}</p></div><button class="btn" id="pxResumeOpen">${recent?'Mở lại bài':'Mở module'} ${icon('modules')}</button>`;$('pxResumeOpen').onclick=()=>openModule(m.id)}
const curriculum=node('div','ux-curriculum');curriculum.append(cards.modules,cards.topics);move('modules',curriculum);
move('practice',$('study-lab'));move('cards',$('formula-cards'));move('roadmap',cards.roadmap,root.querySelector('.cp-pace-details'));move('schedule',cards.schedule);move('review',cards.review);move('mocks',cards.mock);
const analytics=node('div','ux-analytics-grid');analytics.append(cards.heatmap,cards.milestones);move('analytics',analytics);move('journal',cards.journal);move('settings',$('settings'));$('settings').open=true;
root.querySelectorAll(':scope>.cp-deck,:scope>.cp-workspace,:scope>.cp-lower').forEach(n=>n.remove());root.append(root.querySelector('footer'));
const nav=sidebar.querySelector('nav');nav.innerHTML=routes.map(([id,label],i)=>`${[0,4,7].includes(i)?`<div class="ux-nav-label">${i===0?'HỌC TẬP':i===4?'KẾ HOẠCH':'CÁ NHÂN'}</div>`:''}<a href="#/${id}" data-ux-route="${id}" title="${label}"><span class="nav-icon">${icon(id)}</span><span class="nav-label">${label}</span>${id==='modules'?'<span class="ux-nav-count">133</span>':''}</a>`).join('');sidebar.querySelector('.side-caption')?.remove();
const skip=document.querySelector('.skip-link');if(skip){skip.href='#/modules';skip.dataset.uxRoute='modules'}
const mobile=node('nav','ux-mobile-nav',routes.slice(0,4).map(([id,label])=>`<button data-ux-route="${id}">${icon(id)}<span>${label}</span></button>`).join('')+`<button id="uxMoreOpen">${icon('more')}<span>Thêm</span></button>`);mobile.setAttribute('aria-label','Điều hướng trên điện thoại');root.append(mobile);
const topbar=root.querySelector('.cp-topbar');topbar.prepend(node('div','ux-breadcrumb','Không gian học <span>/</span> <strong id="uxBreadcrumb">Hôm nay</strong>'));
const search=node('button','ux-global-search',`${icon('search')}<span>Tìm module hoặc thao tác…</span><kbd>Ctrl K</kbd>`);search.id='uxSearchOpen';search.setAttribute('aria-label','Tìm module hoặc thao tác (Ctrl K)');topbar.querySelector('.cp-top-actions').prepend(search);
header.querySelector('h1').tabIndex=-1;
function heading(){const r=routeMap.get(current)||routes[0];$('uxBreadcrumb').textContent=r[1];header.querySelector('.cp-eyebrow').textContent=current==='today'?'YOUR DAILY STUDY SPACE':'CHARTERPREP / '+r[1].toLocaleUpperCase('vi-VN');header.querySelector('h1').textContent=r[2];header.querySelector('.sub').textContent=r[3];document.querySelectorAll('[data-ux-route]').forEach(a=>{const active=a.dataset.uxRoute===current;a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('uxMoreOpen').classList.toggle('active',!['today','modules','practice','cards'].includes(current))}
function navigate(id,{history=true,focus=false}={}){if(!routeMap.has(id))id='today';if(current===id){heading();return}if(current)positions[current]=window.scrollY;current=id;Object.entries(pages).forEach(([key,p])=>p.hidden=key!==id);heading();if(history&&location.hash!=='#/'+id)window.history.pushState(null,'','#/'+id);if(focus)header.querySelector('h1').focus({preventScroll:true});window.scrollTo?.({top:positions[id]||0,behavior:'instant'})}
const hashRoute=()=>{const id=location.hash.replace(/^#\/?/,'');return id==='study-lab'?'practice':id==='formula-cards'?'cards':routeMap.has(id)?id:'today'};
addEventListener('hashchange',()=>navigate(hashRoute(),{history:false}));addEventListener('popstate',()=>navigate(hashRoute(),{history:false}));
document.addEventListener('click',e=>{const a=e.target.closest('[data-ux-route]');if(!a)return;e.preventDefault();$('uxMore')?.close();navigate(a.dataset.uxRoute,{focus:true})});
$('cpSyncTop').onclick=$('cpProfileTop').onclick=()=>navigate('settings',{focus:true});
const appearance=node('section','ux-appearance',`<div><h3>Giao diện & cảm giác đọc</h3><p>Chọn nền phù hợp với ánh sáng nơi bạn học.</p></div><div class="ux-theme-choice" aria-label="Chế độ giao diện">${[['light','Sáng'],['dark','Tối'],['system','Hệ thống']].map(([v,t])=>`<button data-ux-theme="${v}">${t}</button>`).join('')}</div>`);pages.settings.prepend(appearance);
const more=node('dialog','ux-more',`<button class="ux-more-close" aria-label="Đóng menu">×</button><h2>Không gian học</h2><div class="ux-more-grid">${routes.slice(4).map(([id,label])=>`<button data-ux-route="${id}">${icon(id)}<span>${label}</span></button>`).join('')}</div>`);more.id='uxMore';more.setAttribute('aria-label','Các màn hình khác');document.body.append(more);$('uxMoreOpen').onclick=()=>more.showModal();more.querySelector('.ux-more-close').onclick=()=>more.close();
const filters=node('div','ux-module-filters', [['all','Tất cả'],['todo','Chưa xong'],['done','Đã hoàn thành'],['due','Đến hạn ôn'],['hard','Cần chú ý']].map(([v,t])=>`<button data-ux-filter="${v}" aria-pressed="${v==='all'}">${t}</button>`).join(''));
const controls=node('div','ux-list-controls','<span id="uxModuleCount" role="status"></span><div><button id="uxExpand">Mở tất cả</button><button id="uxCollapse">Thu gọn</button></div><div class="ux-density" aria-label="Mật độ danh sách"><button data-ux-density="comfortable">Thoáng</button><button data-ux-density="compact">Gọn</button></div>');
$('moduleGroups').before(filters,controls);const empty=node('div','ux-module-empty','<strong>Chưa có module phù hợp</strong><p>Thử từ khóa khác hoặc bỏ bộ lọc để xem toàn bộ bài học.</p><button class="btn ghost" id="uxClearFilters">Bỏ bộ lọc</button>');empty.hidden=true;$('moduleGroups').after(empty);
const explorerToolbar=node('div','px-explorer-toolbar');const searchbar=cards.modules.querySelector('.searchbar');searchbar.before(explorerToolbar);explorerToolbar.append(searchbar,filters,controls);
function matches(m){if(filter==='todo')return !progress[m.id];if(filter==='done')return !!progress[m.id];if(filter==='due')return !!progress[m.id]&&CharterPrep.reviewDue(m)<=CharterPrep.localDay();if(filter==='hard'){const q=StudyLab.qStats(m.id);return(difficulty[m.id]||0)>=4||q.total>=10&&q.accuracy<.7}return true}
function decorateModules(){let count=0;const groups=$('moduleGroups');groups.querySelectorAll('[data-mid]').forEach(row=>{const m=MODULES.find(m=>m.id===row.dataset.mid);row.hidden=!matches(m);if(!row.hidden)count++;const name=row.querySelector('.mname');name.tabIndex=0;name.setAttribute('role','button');name.setAttribute('aria-label','Mở chi tiết: '+m.name);name.onclick=()=>openModule(m.id);name.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openModule(m.id)}};if(!row.querySelector('.ux-row-open')){const b=node('button','ux-row-open','↗');b.setAttribute('aria-label','Chi tiết '+m.name);b.onclick=()=>openModule(m.id);row.append(b)}});groups.querySelectorAll('.topic-block').forEach(group=>{group.hidden=![...group.querySelectorAll('[data-mid]')].some(r=>!r.hidden);if(filter!=='all'){group.querySelector('.module-list').classList.add('open');group.querySelector('.topic-block-head').setAttribute('aria-expanded','true')}});groups.querySelectorAll('.empty-hint').forEach(n=>n.hidden=true);empty.hidden=count>0;$('uxModuleCount').textContent=count+' / 133 module';filters.querySelectorAll('button').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.uxFilter===filter)))}
filters.onclick=e=>{const b=e.target.closest('[data-ux-filter]');if(b){filter=b.dataset.uxFilter;decorateModules()}};
$('uxClearFilters').onclick=()=>{filter='all';$('searchInput').value='';$('filterSelect').value='ALL';renderModules()};
$('uxExpand').onclick=()=>{TOPICS.forEach(t=>openTopics.add(t));renderModules()};$('uxCollapse').onclick=()=>{filter='all';openTopics.clear();$('searchInput').value='';renderModules()};
document.addEventListener('click',e=>{const t=e.target.closest('[data-ux-theme]'),d=e.target.closest('[data-ux-density]');if(t){prefs.theme=t.dataset.uxTheme;savePrefs()}if(d){prefs.density=d.dataset.uxDensity;savePrefs()}});
const priorModules=renderModules;renderModules=function(){priorModules();decorateModules()};
const priorRender=render;render=function(){priorRender();heading();renderResume()};
document.addEventListener('click',e=>{if(e.target.closest('#weakGoBtn')&&$('weakGoBtn').textContent.includes('Chọn topic'))navigate('modules')},true);
const oldJump=jumpToTopic;jumpToTopic=function(topic){filter='all';navigate('modules');return oldJump(topic)};window.jumpToTopic=jumpToTopic;
const oldDay=scrollToDay;scrollToDay=function(day){filter='all';navigate('modules');return oldDay(day)};window.scrollToDay=scrollToDay;
const sheet=node('dialog','ux-module-sheet','<div class="ux-sheet-head"><span>MODULE WORKSPACE</span><button class="cp-icon-btn" id="uxSheetClose" aria-label="Đóng chi tiết module">×</button></div><div class="ux-sheet-body" id="uxSheetBody"></div>');sheet.id='uxModuleSheet';sheet.setAttribute('aria-labelledby','uxSheetTitle');document.body.append(sheet);$('uxSheetClose').onclick=()=>sheet.close();
function openModule(id){const m=MODULES.find(m=>m.id===id);if(!m)return;sheetId=id;prefs.recent=[id,...prefs.recent.filter(x=>x!==id)].slice(0,5);savePrefs();renderResume();renderSheet();if(!sheet.open)sheet.showModal()}
function renderSheet(){const m=MODULES.find(m=>m.id===sheetId);if(!m)return;const q=StudyLab.qStats(m.id),completed=!!progress[m.id],lab=StudyLab.getState(),mistakes=lab.mistakes.filter(x=>x.moduleId===m.id&&!x.resolved).length,flashcards=lab.cards.filter(x=>x.moduleId===m.id).length;
$('uxSheetBody').innerHTML=`<div class="ux-sheet-topic">${esc(m.topic)}</div><h2 id="uxSheetTitle">${esc(m.name)}</h2><div class="ux-sheet-meta">Ngày ${effectiveDay(m)} · ${completed?'Đã hoàn thành':'Chưa hoàn thành'}${completed?' · Ôn tiếp: '+CharterPrep.reviewDue(m):''}</div><button class="btn ux-sheet-primary" id="uxSheetComplete">${completed?'✓ Đã hoàn thành · Bỏ đánh dấu':'Đánh dấu đã hoàn thành'}</button><section class="ux-sheet-section"><h3>Công cụ học tập</h3><div class="ux-sheet-grid"><button id="uxSheetVideo">▶ Video & ghi chú</button><button id="uxSheetQ">＋ Kết quả QBank</button><button id="uxSheetMistake">＋ Ghi câu sai</button><button id="uxSheetCard">＋ Tạo thẻ nhớ</button></div></section><section class="ux-sheet-section"><h3>Kết quả của module</h3><div class="ux-sheet-row"><span>QBank</span><strong>${q.total?Math.round(q.accuracy*100)+'% · '+q.correct+'/'+q.total+' câu':'Chưa có kết quả'}</strong></div><div class="ux-sheet-progress"><i style="width:${q.total?q.accuracy*100:0}%"></i></div><div class="ux-sheet-row"><span>Câu sai cần ôn</span><strong>${mistakes}</strong></div><div class="ux-sheet-row"><span>Thẻ nhớ đã tạo</span><strong>${flashcards}</strong></div></section><section class="ux-sheet-section"><h3>Điều chỉnh kế hoạch</h3><label class="ux-sheet-row">Ngày học<select id="uxSheetDay" aria-label="Ngày học của module">${Array.from({length:meta.totalDays},(_,i)=>`<option value="${i+1}" ${effectiveDay(m)===i+1?'selected':''}>Ngày ${i+1}</option>`).join('')}</select></label><div class="ux-sheet-row"><span>Độ khó cảm nhận</span><div class="ux-sheet-stars">${[1,2,3,4,5].map(n=>`<button data-ux-rate="${n}" aria-label="Độ khó ${n} trên 5" aria-pressed="${difficulty[m.id]===n}" class="${(difficulty[m.id]||0)>=n?'active':''}">★</button>`).join('')}</div></div><p class="ux-sheet-note">Chạm mức đang chọn để bỏ đánh giá. Module từ 4 sao được đưa vào bộ lọc Cần chú ý.</p></section>`;
const index=MODULES.findIndex(x=>x.id===m.id);$('uxSheetBody').insertAdjacentHTML('beforeend',`<nav class="px-module-navigation" aria-label="Chuyển module"><button id="pxModulePrevious" ${index===0?'disabled':''}>← Bài trước</button><span>${index+1} / ${MODULES.length}</span><button id="pxModuleNext" ${index===MODULES.length-1?'disabled':''}>Bài tiếp theo →</button></nav><p class="px-save-status" id="pxSaveStatus" role="status"></p>`);
const changeModule=offset=>{const next=MODULES[index+offset];if(next){openModule(next.id);sheet.scrollTop=0;$('uxSheetTitle').tabIndex=-1;$('uxSheetTitle').focus({preventScroll:true})}};$('pxModulePrevious').onclick=()=>changeModule(-1);$('pxModuleNext').onclick=()=>changeModule(1);
$('uxSheetComplete').onclick=()=>{toggleModule(m.id);renderSheet();$('uxSheetComplete').focus();let saved=false;try{saved=!!JSON.parse(localStorage.getItem('cfa-progress')||'{}')[m.id]===!!progress[m.id]}catch{}$('pxSaveStatus').textContent=saved?(progress[m.id]?'Đã lưu trạng thái hoàn thành trên thiết bị.':'Đã bỏ đánh dấu hoàn thành.'): 'Chưa lưu được trên thiết bị. Hãy sao lưu dữ liệu trước khi đóng trang.'};$('uxSheetDay').onchange=e=>{moveModuleToDay(m.id,Number(e.target.value));renderSheet();renderResume();$('uxSheetDay').focus()};sheet.querySelectorAll('[data-ux-rate]').forEach(b=>b.onclick=()=>{const n=Number(b.dataset.uxRate);setDifficulty(m.id,n);renderWeakCard();renderSheet();sheet.querySelector(`[data-ux-rate="${n}"]`).focus()});
const next=fn=>()=>{sheet.close();fn(m.id)};$('uxSheetVideo').onclick=next(id=>window.openVideoModal(id));$('uxSheetQ').onclick=next(StudyLab.openQbank);$('uxSheetMistake').onclick=next(StudyLab.openMistake);$('uxSheetCard').onclick=next(StudyLab.openCard);
}
const command=node('dialog','ux-command','<div class="ux-command-input">'+icon('search')+'<input id="uxCommandInput" placeholder="Tên module, chủ đề hoặc thao tác…" autocomplete="off" role="combobox" aria-label="Tìm module hoặc thao tác" aria-expanded="true" aria-controls="uxCommandResults" aria-autocomplete="list"><button class="cp-icon-btn" id="uxCommandClose" aria-label="Đóng tìm kiếm">×</button></div><div class="ux-command-results" id="uxCommandResults" role="listbox" aria-label="Kết quả tìm kiếm"></div><div class="ux-command-footer"><span>↑ ↓ Di chuyển</span><span>↵ Mở kết quả</span><span>Esc Đóng</span><span id="uxSearchCount" role="status"></span></div>');command.id='uxCommand';command.setAttribute('aria-label','Tìm kiếm nhanh');document.body.append(command);$('uxCommandClose').onclick=()=>command.close();
const normalize=s=>String(s).normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/đ/g,'d').toLowerCase();let results=[],selected=0;
function commandResults(){const query=normalize($('uxCommandInput').value.trim()),terms=query.split(/\s+/).filter(Boolean),match=s=>terms.every(t=>normalize(s).includes(t));const actions=routes.map(([id,label])=>({label,meta:'Đi đến màn hình',icon:id,run:()=>navigate(id,{focus:true})}));actions.push({label:'Bắt đầu chế độ tập trung',meta:'Pomodoro · 25 phút',icon:'today',run:()=>openFocusMode()},{label:'Ghi kết quả QBank',meta:'Thêm lượt luyện tập',icon:'practice',run:()=>StudyLab.openQbank()},{label:'Tạo thẻ nhớ mới',meta:'Công thức & kiến thức',icon:'cards',run:()=>StudyLab.openCard()});results=actions.filter(a=>!query||match(a.label+' '+a.meta));if(query)results.push(...MODULES.filter(m=>match(m.name+' '+m.topic+' '+m.id)).map(m=>({label:m.name,meta:m.topic+' · Ngày '+effectiveDay(m),icon:'modules',run:()=>openModule(m.id)})));selected=0;$('uxCommandResults').innerHTML=results.map((r,i)=>`<div class="ux-command-item" id="ux-result-${i}" role="option" aria-selected="${i===0}" data-result="${i}">${icon(r.icon)}<div>${esc(r.label)}<small>${esc(r.meta)}</small></div><span aria-hidden="true">↵</span></div>`).join('')||'<div class="lab-empty">Không tìm thấy. Thử một từ trong tên module.</div>';$('uxSearchCount').textContent=results.length+' kết quả';selectResult(0)}
function selectResult(index){selected=Math.max(0,Math.min(results.length-1,index));command.querySelectorAll('[data-result]').forEach(n=>n.setAttribute('aria-selected',String(Number(n.dataset.result)===selected)));if(results.length)$('uxCommandInput').setAttribute('aria-activedescendant','ux-result-'+selected);else $('uxCommandInput').removeAttribute('aria-activedescendant')}
function activateResult(index){const result=results[index];if(result){command.close();result.run()}}
function openCommand(){if(root.classList.contains('locked')||document.querySelector('dialog[open]')||document.querySelector('.modal-overlay.open,.focus-overlay.open,#videoModalOverlay.open'))return;$('uxCommandInput').value='';commandResults();command.showModal();$('uxCommandInput').focus()}
search.onclick=openCommand;$('uxCommandInput').oninput=commandResults;$('uxCommandResults').onclick=e=>{const n=e.target.closest('[data-result]');if(n)activateResult(Number(n.dataset.result))};
$('uxCommandInput').onkeydown=e=>{if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();selectResult((selected+(e.key==='ArrowDown'?1:-1)+results.length)%Math.max(1,results.length));$('ux-result-'+selected)?.scrollIntoView({block:'nearest'})}if(e.key==='Enter'){e.preventDefault();activateResult(selected)}};
document.addEventListener('keydown',e=>{if(root.classList.contains('locked'))return;const typing=e.target.matches('input,textarea,select,[contenteditable="true"]');if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'||e.key==='/'&&!typing&&!e.ctrlKey&&!e.metaKey){e.preventDefault();e.stopImmediatePropagation();if(command.open)command.close();else openCommand()}},true);
for(const d of [command,sheet,more])d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()}});
const running=node('div','ux-running-bar','<span>Phiên học <strong id="uxRunningTime">00:00:00</strong></span><button id="uxRunningPause" aria-label="Tạm dừng phiên học">Ⅱ</button><button data-ux-route="today">Mở →</button>');running.hidden=true;root.append(running);$('uxRunningPause').onclick=()=>$('timerBtn').click();const priorTimer=updateTimerDisplay;updateTimerDisplay=function(){priorTimer();running.hidden=!CharterPrep.getSession().since||current==='today';$('uxRunningTime').textContent=$('cpLiveSession').textContent};
applyPrefs();renderModules();renderResume();navigate(hashRoute(),{history:false});updateTimerDisplay();
window.CharterExperience={navigate,openModule,openCommand,refreshHeading:heading,getRoute:()=>current,getPreferences:()=>({...prefs}),getFilter:()=>filter};
})();
