(()=>{
'use strict';
const $=id=>document.getElementById(id),storageKey='charter-pace-alert-v1',msDay=86400000;
const parse=s=>new Date(s+'T12:00:00'),shift=(s,n)=>{const d=parse(s);d.setDate(d.getDate()+n);return CharterPrep.localDay(d)};
const targetDate=()=>meta.examDate||meta.mockDate||(meta.programStart?shift(meta.programStart,Math.max(0,(Number(meta.totalDays)||1)-1)):null);
function metrics(){const insight=window.StudyInsights?.metrics?.(),target=targetDate();if(!insight||!target||!insight.finish||!insight.remaining)return{lateDays:0,target,insight};const lateDays=Math.max(0,Math.ceil((parse(insight.finish)-parse(target))/msDay));return{lateDays,target,insight,targetKind:meta.examDate?'ngày thi':meta.mockDate?'ngày mock':'cuối lộ trình'}}
const alert=document.createElement('aside');alert.id='paceAlert';alert.className='pace-alert';alert.hidden=true;alert.setAttribute('role','alertdialog');alert.setAttribute('aria-labelledby','paceAlertTitle');alert.setAttribute('aria-describedby','paceAlertText');alert.innerHTML='<div><strong id="paceAlertTitle">Nhịp học đang chậm</strong><span id="paceAlertText"></span></div><button class="btn" id="paceAlertPlan">Xem kế hoạch học bù</button><button class="pace-alert-later" id="paceAlertLater">Để sau</button>';document.body.append(alert);
let currentSignature='',previewOpen=false;
function seen(){try{return JSON.parse(localStorage.getItem(storageKey)||'{}')}catch{return{}}}
function hide(save=true){previewOpen=false;alert.hidden=true;if(save&&currentSignature)localStorage.setItem(storageKey,JSON.stringify({signature:currentSignature,at:new Date().toISOString()}))}
function check(force=false){const m=metrics();if(previewOpen&&!alert.hidden)return m;const today=CharterPrep.localDay();currentSignature=m.lateDays?`${today}|${m.target}|${m.lateDays}`:'';if(!location.hash.startsWith('#/today')||!m.lateDays||(!force&&seen().signature===currentSignature)){alert.hidden=true;return m}const pace=m.insight.pace.toFixed(1);$('paceAlertText').textContent=`Với nhịp ${pace} module/ngày, bạn dự kiến hoàn thành chậm ${m.lateDays} ngày so với ${m.targetKind}.`;alert.hidden=false;return m}
function preview(){const m=metrics();$('paceAlertText').textContent=m.lateDays?`Với nhịp ${m.insight.pace.toFixed(1)} module/ngày, bạn dự kiến hoàn thành chậm ${m.lateDays} ngày so với ${m.targetKind}.`:'Bản xem thử: với nhịp hiện tại, bạn dự kiến hoàn thành chậm 4 ngày so với ngày thi.';currentSignature='';previewOpen=true;alert.hidden=false}
$('paceAlertLater').onclick=()=>hide(true);$('paceAlertPlan').onclick=()=>{hide(true);CharterExperience.navigate('roadmap',{focus:true});setTimeout(()=>$('labCatchup')?.click(),250)};
const setting=document.createElement('section');setting.className='card pace-preview-setting';setting.setAttribute('translate','no');setting.innerHTML='<div><h2>Cảnh báo pace học</h2><p>Xem trước cách web thông báo khi tiến độ dự kiến chậm hơn ngày thi hoặc lộ trình.</p></div><button class="btn ghost" id="paceAlertPreview">Xem thử cảnh báo</button>';const appearance=$('ux-page-settings')?.querySelector('.ux-appearance');appearance?.after(setting);$('paceAlertPreview').onclick=()=>{CharterExperience.navigate('today',{focus:true});setTimeout(preview,250)};
let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(()=>check(),350)};addEventListener('charter-route',schedule);addEventListener('charter-goal-change',schedule);addEventListener('focus',schedule);schedule();window.PaceAlert={metrics,check,hide,preview};
})();
