(()=>{
'use strict';
const $=id=>document.getElementById(id),key='charter-pomo-v2';
const defaults={focus:25,short:5,long:15,interval:4,autoBreak:true,autoFocus:true,sound:true,tone:'ring',volume:100,ringSeconds:15,warning:true};
let saved;try{saved=JSON.parse(localStorage.getItem(key))}catch{}
let state=saved||{mode:'focus',remaining:1500000,end:null,checkpoint:null,rounds:0,settings:defaults};state.settings={...defaults,...state.settings};
const persist=()=>localStorage.setItem(key,JSON.stringify(state));
const duration=()=>state.settings[state.mode]*60000;
const panel=document.createElement('section');panel.className='pomo-panel';panel.innerHTML='<div class="pomo-top"><strong>Nhịp tập trung</strong><div><button id="pomoReport">Thống kê</button><button id="pomoSettings">Cài đặt</button></div></div><div class="pomo-modes"><button data-mode="focus">Tập trung</button><button data-mode="short">Nghỉ ngắn</button><button data-mode="long">Nghỉ dài</button></div><strong id="pomoDisplay">25:00</strong><div class="pomo-description" id="pomoStatus"></div><div class="pomo-actions"><button class="btn" id="pomoToggle">Bắt đầu</button><button class="btn ghost" id="pomoReset">Đặt lại</button></div><p class="pomo-description">Tự lưu thời gian tập trung. Giờ nghỉ không tính vào giờ học.</p>';
$('timerBtn').closest('.card').append(panel);['pomoStatus','pomoToggle'].forEach(id=>$(id).setAttribute('translate','no'));
const dialog=document.createElement('dialog');dialog.className='pomo-dialog';dialog.setAttribute('aria-label','Cài đặt Pomodoro');dialog.innerHTML='<div class="lab-dialog-head"><h2>Cài đặt nhịp học</h2><button type="button" class="lab-dialog-close" aria-label="Đóng">×</button></div><form id="pomoForm"><div class="pomo-fields">'+[['focus','Tập trung'],['short','Nghỉ ngắn'],['long','Nghỉ dài'],['interval','Số phiên trước nghỉ dài']].map(([id,label])=>`<label>${label}${id==='interval'?'':' (phút)'}<input name="${id}" type="number" min="1" max="${id==='interval'?12:180}" required></label>`).join('')+'</div>'+[['autoBreak','Tự bắt đầu giờ nghỉ'],['autoFocus','Tự bắt đầu phiên học tiếp'],['sound','Chuông báo hết giờ học và giờ nghỉ']].map(([id,label])=>`<label class="pomo-option"><input type="checkbox" name="${id}">${label}</label>`).join('')+'<div class="pomo-actions"><button type="button" class="btn ghost" id="pomoSound">Nghe thử chuông</button><button class="btn" type="submit">Lưu cài đặt</button></div></form>';document.body.append(dialog);dialog.querySelector('.lab-dialog-close').onclick=()=>dialog.close();
const report=document.createElement('dialog');report.className='pomo-dialog';report.setAttribute('aria-label','Thống kê tập trung');document.body.append(report);
let audio;
function unlock(){try{audio??=new (window.AudioContext||window.webkitAudioContext)();audio.resume()}catch{}}
function bell(){if(!state.settings.sound)return;unlock();if(!audio)return;const notes=[523.25,659.25,783.99,1046.5];notes.forEach((frequency,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.24;o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.16,t+.025);g.gain.exponentialRampToValueAtTime(.001,t+.52);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.56)})}
function credit(end){if(state.mode!=='focus'||!state.checkpoint)return;let cursor=state.checkpoint;state.checkpoint=end;persist();while(cursor<end){const midnight=new Date(cursor);midnight.setHours(24,0,0,0);const stop=Math.min(end,midnight.getTime()),minutes=(stop-cursor)/60000,date=CharterPrep.localDay(cursor);timeLog[date]=(timeLog[date]||0)+minutes;sessions.push({date,startHour:new Date(cursor).getHours(),minutes,source:'pomodoro',moduleId:state.moduleId||null,moduleName:MODULES.find(m=>m.id===state.moduleId)?.name||''});cursor=stop}saveTimeLog();saveSessions();render();}
function pause(){if(!state.end)return;const end=Math.min(Date.now(),state.end);credit(end);state.remaining=Math.max(0,state.end-Date.now());state.end=null;state.checkpoint=null;persist()}
function start(){unlock();if(CharterPrep.getSession().since)$('timerBtn').click();if(CharterPrep.sessionMs()>0)$('cpTimerCommit').click();state.remaining=state.remaining||duration();state.end=Date.now()+state.remaining;state.checkpoint=Date.now();persist();draw()}
function draw(){const left=state.end?Math.max(0,state.end-Date.now()):state.remaining,seconds=Math.ceil(left/1000),en=document.body.dataset.language==='en';$('pomoDisplay').textContent=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');$('pomoToggle').textContent=state.end?(en?'Pause':'Tạm dừng'):state.remaining<duration()?(en?'Continue':'Tiếp tục'):(en?'Start':'Bắt đầu');$('pomoStatus').textContent=en?`${state.rounds} sessions completed · ${state.mode==='focus'?'Focus on one task':'Relax and recharge'}`:`${state.rounds} phiên hoàn thành · ${state.mode==='focus'?'Tập trung vào một việc':'Thả lỏng và nạp lại năng lượng'}`;panel.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===state.mode)));['timerBtn','goalSessionToggle','cpTimerCommit'].forEach(id=>{if(state.end)$(id).disabled=true;else if(id!=='cpTimerCommit')$(id).disabled=false});if(typeof updateTab==='function')updateTab()}
let lastTabKey='';
function updateTab(){const left=state.end?Math.max(0,state.end-Date.now()):state.remaining,seconds=Math.ceil(left/1000),clock=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0'),key=`${state.end?'run':'stop'}|${state.mode}|${clock}`;if(key===lastTabKey)return;lastTabKey=key;let link=document.querySelector('link[rel="icon"]');if(!link){link=document.createElement('link');link.rel='icon';document.head.append(link)}const color=state.mode==='focus'?'#d84b55':'#28a879',svg=`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><circle cx="16" cy="16" r="13" fill="${color}"/><path d="m10 16 4 4 8-8" fill="none" stroke="#fff" stroke-width="2.7" stroke-linecap="round" stroke-linejoin="round"/></svg>`;const href='data:image/svg+xml;charset=utf-8,'+encodeURIComponent(svg);if(link.href!==href)link.href=href;const title=state.end?`${state.mode==='focus'?'🔴':'🟢'} ${clock} · ${state.mode==='focus'?'Tập trung':'Nghỉ'} · CharterPrep`:'CharterPrep';if(document.title!==title)document.title=title}
const originalTabUpdate=updateTab;let tabModeKey='';updateTab=function(){const modeKey=`${state.end?'run':'stop'}|${state.mode}`;if(state.end&&modeKey===tabModeKey)return;tabModeKey=modeKey;originalTabUpdate()};
function tick(){const stored=localStorage.getItem(key);if(stored)try{state=JSON.parse(stored);state.settings={...defaults,...state.settings}}catch{}if(state.end&&Date.now()>=state.end){credit(state.end);const wasFocus=state.mode==='focus';if(wasFocus)state.rounds++;state.mode=wasFocus?(state.rounds%state.settings.interval===0?'long':'short'):'focus';state.remaining=duration();state.end=null;state.checkpoint=null;persist();bell();state.warned=false;persist();if(wasFocus?state.settings.autoBreak:state.settings.autoFocus)start()}draw()}
$('pomoToggle').onclick=()=>{if(state.end)pause();else start();draw()};$('pomoReset').onclick=()=>{pause();state.remaining=duration();state.warned=false;persist();draw()};panel.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{pause();state.mode=b.dataset.mode;state.remaining=duration();state.warned=false;persist();draw()});
$('pomoSettings').onclick=()=>{for(const [name,value]of Object.entries(state.settings)){const input=$('pomoForm').elements.namedItem(name);if(input)typeof value==='boolean'?input.checked=value:input.value=value}dialog.showModal()};$('pomoForm').onsubmit=e=>{e.preventDefault();pause();for(const name of ['focus','short','long','interval'])state.settings[name]=Number(e.target.elements.namedItem(name).value);for(const name of ['autoBreak','autoFocus','sound','warning'])state.settings[name]=e.target.elements.namedItem(name).checked;state.settings.tone=e.target.elements.tone.value;state.settings.volume=Number(e.target.elements.volume.value);state.settings.ringSeconds=Number(e.target.elements.ringSeconds.value);state.remaining=duration();state.warned=false;persist();draw();dialog.close()};$('pomoSound').onclick=()=>{unlock();bell()};
function showReport(){const entries=Object.entries(timeLog).filter(([,v])=>v>0).sort(([a],[b])=>b.localeCompare(a)),total=entries.reduce((n,[,v])=>n+v,0);let streak=0,d=new Date();if(!(timeLog[CharterPrep.localDay(d)]>0))d.setDate(d.getDate()-1);while(timeLog[CharterPrep.localDay(d)]>0){streak++;d.setDate(d.getDate()-1)}const days=Array.from({length:7},(_,i)=>{const day=new Date();day.setDate(day.getDate()-6+i);return{label:day.toLocaleDateString('vi-VN',{weekday:'short'}),value:timeLog[CharterPrep.localDay(day)]||0}}),max=Math.max(60,...days.map(d=>d.value));report.innerHTML='<div class="lab-dialog-head"><h2>Thống kê học tập</h2><button class="lab-dialog-close" aria-label="Đóng">×</button></div><div class="pomo-summary">'+[[ (total/60).toFixed(1),'giờ tập trung'],[entries.length,'ngày học'],[streak,'ngày liên tiếp']].map(([n,l])=>`<div><strong>${n}</strong>${l}</div>`).join('')+'</div><h3>Giờ học · 7 ngày gần đây</h3><div class="pomo-chart">'+days.map(d=>`<div class="pomo-bar"><span>${Math.round(d.value)}′</span><i style="height:${d.value/max*125}px"></i><span>${d.label}</span></div>`).join('')+'</div><p class="pomo-description">Bao gồm phiên học đã lưu và thời gian Pomodoro đã ghi nhận.</p><ul class="pomo-history">'+entries.slice(0,30).map(([date,min])=>`<li><span>${date.split('-').reverse().join('/')}</span><strong>${Math.round(min)} phút</strong></li>`).join('')+'</ul>';report.querySelector('button').onclick=()=>report.close();report.showModal()}
$('pomoReport').onclick=showReport;
addEventListener('charter-language-change',draw);
// A single timer owns focus mode too; opening it cannot start an untracked second timer.
const oldPomo=document.querySelector('.cp-pomodoro');if(oldPomo){oldPomo.style.display='none';const link=document.createElement('button');link.className='btn';link.textContent='Mở Pomodoro trong phiên học';link.onclick=()=>{closeFocusMode();location.hash='/today';panel.scrollIntoView({behavior:'smooth',block:'center'})};oldPomo.after(link)}
// Module pickers: checkbox change owns selection; dialog clicks must not revert it.
for(const id of ['dailyPlanModules','emailTomorrowModules']){
 const select=$(id);if(!select)continue;
 const parent=select.parentElement;
 if(parent.tagName==='LABEL'){
  const group=document.createElement('div');group.className=parent.className;
  group.setAttribute('role','group');group.setAttribute('aria-label',parent.firstChild?.textContent.trim()||'Chọn module');
  group.append(...parent.childNodes);parent.replaceWith(group);
 }
 select.hidden=true;select.style.display='none';
 const list=document.createElement('div');list.className='module-picker';select.after(list);
 const hint=select.parentElement.querySelector('small');if(hint)hint.textContent='Bấm chọn từng module. Để trống để dùng gợi ý tự động.';
 let rows=[];
 function refresh(){
  const options=[...select.options];
  if(options.length!==rows.length||options.some((option,i)=>rows[i].option!==option)){
   rows=options.map(option=>{
    const row=document.createElement('label'),input=document.createElement('input'),name=document.createElement('span');input.type='checkbox';
    input.onchange=()=>{option.selected=input.checked;select.dispatchEvent(new Event('change',{bubbles:true}))};
    row.append(input,name);return {row,input,name,option};
   });list.replaceChildren(...rows.map(r=>r.row));
  }
  for(const {input,name,option}of rows){input.checked=option.selected;input.disabled=select.disabled||option.disabled;if(name.textContent!==option.textContent)name.textContent=option.textContent}
 }
 new MutationObserver(refresh).observe(select,{childList:true,subtree:true,attributes:true,characterData:true});
 select.addEventListener('change',refresh);refresh();
}
// End module pickers.
// POMODORO_CONTROLS
setInterval(tick,1000);addEventListener('focus',tick);tick();updateTab();window.CharterPomodoro={tick};

const overview=document.querySelector('.today-overview'),heroClock=document.querySelector('.goal-session-clock');if(overview&&heroClock)overview.after(heroClock);
const savedLabel=document.createElement('small');savedLabel.id='heroSavedTime';heroClock?.append(savedLabel);
const displayBefore=updateTimerDisplay;updateTimerDisplay=function(){displayBefore();const minutes=Math.floor(timeLog[CharterPrep.localDay()]||0);savedLabel.textContent='Đã lưu hôm nay: '+Math.floor(minutes/60)+' giờ '+minutes%60+' phút · Đồng hồ hiển thị phiên hiện tại'};updateTimerDisplay();

if(StudyPreservation.recoveredMinutes>0){const notice=document.createElement('p');notice.className='study-recovery-notice';notice.setAttribute('role','status');notice.textContent='Đã khôi phục '+Math.round(StudyPreservation.recoveredMinutes)+' phút từ nhật ký học còn lưu trên thiết bị.';$('timerWeek').after(notice)}
const collapse=document.querySelector('.studio-collapse');if(collapse){const glyph=()=>{collapse.innerHTML='<svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="4" width="18" height="16" rx="3"/><path d="M9 4v16"/><path d="'+(document.body.classList.contains('studio-compact')?'m13 9 3 3-3 3':'m16 9-3 3 3 3')+'"/></svg>';collapse.title=collapse.getAttribute('aria-label')};collapse.addEventListener('click',glyph);glyph()}

const recoveryExport=document.createElement('button');recoveryExport.className='btn ghost';recoveryExport.type='button';recoveryExport.id='studyRecoveryExport';recoveryExport.textContent='Tải dữ liệu để khôi phục giờ học';recoveryExport.onclick=()=>{
 const data={version:1,exportedAt:new Date().toISOString(),timeLog,sessions,activeSession:CharterPrep.getSession(),stored:{},backups:[]};
 for(const key of ['cfa-timelog','cfa-sessions','cfa-cp-session','cfa-timer-start','charter-study-hours-archive','charter-pomo-v2']){const value=localStorage.getItem(key);if(value!==null)try{data.stored[key]=JSON.parse(value)}catch{data.stored[key]=value}}
 for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(key.startsWith('charter-study-backup-'))try{const backup=JSON.parse(localStorage.getItem(key));data.backups.push({at:backup.at,timeLog:backup.data?.['cfa-timelog'],sessions:backup.data?.['cfa-sessions'],activeSession:backup.data?.['cfa-cp-session']})}catch{}}
 const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=url;link.download='CharterPrep-khoi-phuc-gio-hoc.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
};$('timerWeek').after(recoveryExport);
const manualBtn=document.createElement('button');manualBtn.className='btn ghost';manualBtn.type='button';manualBtn.id='manualStudyTime';manualBtn.textContent='Nhập giờ đã học';$('timerWeek').after(manualBtn);
const manualDialog=document.createElement('dialog');manualDialog.className='pomo-dialog';manualDialog.setAttribute('aria-label','Nhập giờ đã học');manualDialog.innerHTML='<div class="lab-dialog-head"><h2>Nhập giờ đã học</h2><button type="button" class="lab-dialog-close" aria-label="Đóng">×</button></div><form id="manualStudyForm"><p class="pomo-description">Cộng thêm vào hôm nay, không xoá thời gian đã lưu.</p><div class="pomo-fields"><label>Giờ<input name="hours" type="number" min="0" max="24" step="1" value="4" required></label><label>Phút<input name="minutes" type="number" min="0" max="59" step="1" value="0" required></label></div><p id="manualStudyError" class="lab-form-error" role="alert"></p><div class="pomo-actions"><button type="button" class="btn ghost" id="manualStudyCancel">Huỷ</button><button type="submit" class="btn">Cộng vào thống kê</button></div></form>';
document.body.append(manualDialog);manualDialog.querySelector('.lab-dialog-close').onclick=()=>manualDialog.close();$('manualStudyCancel').onclick=()=>manualDialog.close();manualBtn.onclick=()=>{manualDialog.querySelector('[name="hours"]').value=4;manualDialog.querySelector('[name="minutes"]').value=0;$('manualStudyError').textContent='';manualDialog.showModal()};
$('manualStudyForm').onsubmit=e=>{e.preventDefault();const hours=Number(e.target.elements.hours.value)||0,minutes=Number(e.target.elements.minutes.value)||0,total=hours*60+minutes;if(!Number.isInteger(hours)||!Number.isInteger(minutes)||hours<0||hours>24||minutes<0||minutes>59||total<1){$('manualStudyError').textContent='Nhập ít nhất 1 phút, tối đa 24 giờ.';return}const date=CharterPrep.localDay();timeLog[date]=(timeLog[date]||0)+total;sessions.push({date,startHour:new Date().getHours(),minutes:total,source:'manual'});saveTimeLog();saveSessions();render();updateTimerDisplay();manualDialog.close();toast('Đã cộng '+hours+' giờ '+minutes+' phút vào thống kê hôm nay.')};
})();
