/* A unified study dashboard using existing, personal study records. */
(()=>{
'use strict';
const $=id=>document.getElementById(id),root=$('appRoot'),home=$('ux-page-today'),esc=s=>escapeHtml(String(s??''));
document.body.classList.add('study-studio');
for(const [id,title]of [['moduleGroups','Danh sách module'],['topicBreakdown','Môn học & trọng số'],['mockList','Kết quả thi thử'],['heatmapGrid','Hoạt động học tập'],['milestoneGrid','Cột mốc học tập'],['scheduleList','Khung giờ học'],['weeklyReview','Lịch ôn tập']]){const heading=$(id).closest('.card')?.querySelector('.card-title'),text=heading&&[...heading.childNodes].find(n=>n.nodeType===3&&n.textContent.trim());if(text)text.textContent=' '+title+' '}
const make=(tag,cls,html='')=>{const n=document.createElement(tag);n.className=cls;n.innerHTML=html;return n};
const glyph=path=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${path}"/></svg>`;
const icons={progress:glyph('M4 17l6-6 4 3 6-9M14 5h6v6'),accuracy:glyph('M8 12l3 3 5-6M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0'),time:glyph('M12 7v5l3 2M21 12a9 9 0 1 1-18 0 9 9 0 0 1 18 0'),book:glyph('M5 3h10l4 4v14H5zM9 11h6M9 15h6'),calendar:glyph('M4 5h16v16H4zM8 3v4M16 3v4M4 10h16')};
const stats=make('section','studio-stats',`<article class="studio-stat studio-stat-primary"><h2><i>${icons.progress}</i>Tiến độ học tập</h2><p id="studioProgressHint"></p><div class="studio-stat-number"><strong id="studioProgress">0</strong><span>%</span></div></article><article class="studio-stat"><h2><i>${icons.accuracy}</i>Độ chính xác</h2><p id="studioAccuracyHint"></p><div class="studio-stat-number"><strong id="studioAccuracy">—</strong><span id="studioAccuracyUnit">%</span></div></article><article class="studio-stat"><h2><i>${icons.time}</i>Thời gian đã học</h2><div class="studio-week" id="studioWeek" aria-label="Thời gian học 7 ngày gần nhất"></div><p class="studio-week-detail" id="studioWeekDetail" role="status">Bấm vào một cột để xem chi tiết.</p><div class="studio-stat-number"><strong id="studioMinutes">0</strong><span>phút / 7 ngày</span></div></article>`);stats.setAttribute('aria-label','Tổng quan học tập');
const activity=make('section','studio-activity',`<div class="studio-panel-head"><h2>Hoạt động gần đây</h2><div class="studio-tabs" aria-label="Lọc hoạt động"><button data-studio-filter="all" aria-pressed="true">Tất cả</button><button data-studio-filter="module" aria-pressed="false">Module</button><button data-studio-filter="practice" aria-pressed="false">Luyện tập</button></div></div><div class="studio-table-scroll"><table><thead><tr><th>Nội dung</th><th>Ngày</th><th>Loại</th><th>Kết quả</th></tr></thead><tbody id="studioActivity"></tbody></table></div><div id="studioActivityEmpty" class="studio-empty"><i>${icons.book}</i><strong>Hành trình của bạn bắt đầu từ đây</strong><p>Hoàn thành một module hoặc ghi kết quả QBank để xem hoạt động tại đây.</p><button class="btn" data-ux-route="modules">Mở module học</button></div>`);
const next=make('section','studio-next');next.setAttribute('aria-label','Tiếp tục học');next.append($('pxResume'),$('timerBtn').closest('.card'));
const accuracy=make('section','studio-topic-panel','<div class="studio-panel-head"><h2>Độ chính xác theo môn</h2><span id="studioTopicsCount"></span></div><div id="studioTopics"></div>');
const details=make('details','studio-more','<summary>Tiến độ chi tiết & mục tiêu học tập</summary>');const detailsBody=make('div','studio-more-body');detailsBody.append(home.querySelector('.goal'),home.querySelector('.cp-stats'),$('ringPct').closest('.card'),$('weakCard'));details.append(detailsBody);
home.querySelector('.ux-overview-lower')?.remove();home.replaceChildren(stats,activity,next,$('today'),accuracy,details);
const exam=make('button','studio-exam');exam.id='studioExam';exam.type='button';exam.setAttribute('aria-label','Cài đặt kỳ thi');root.querySelector('.side-bottom').before(exam);exam.onclick=()=>CharterExperience.navigate('settings',{focus:true});
root.querySelector('.side-target').hidden=true;
const collapse=make('button','studio-collapse','‹');collapse.type='button';collapse.setAttribute('aria-label','Thu gọn thanh điều hướng');collapse.setAttribute('aria-expanded','true');root.querySelector('.sidebar').append(collapse);collapse.onclick=()=>{const compact=document.body.classList.toggle('studio-compact');collapse.textContent=compact?'›':'‹';collapse.setAttribute('aria-expanded',String(!compact));collapse.setAttribute('aria-label',compact?'Mở rộng thanh điều hướng':'Thu gọn thanh điều hướng')};
let activityFilter='all';
function drawStats(){const total=MODULES.length,done=MODULES.filter(m=>progress[m.id]).length,q=StudyLab.qStats();$('studioProgress').textContent=total?Math.round(done/total*100):0;$('studioProgressHint').textContent=total?`${done} / ${total} module đã hoàn thành`:'Thêm module để bắt đầu chương trình của bạn.';$('studioAccuracy').textContent=q.total?Math.round(q.accuracy*100):'—';$('studioAccuracyUnit').hidden=!q.total;$('studioAccuracyHint').textContent=q.total?`${q.correct} / ${q.total} câu đúng đã ghi trong QBank`:'Chưa có kết quả QBank để tính.';const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-6+i);return{date:CharterPrep.localDay(d),label:['CN','T2','T3','T4','T5','T6','T7'][d.getDay()]}});const max=Math.max(1,...days.map(d=>timeLog[d.date]||0));const totalMinutes=Math.round(days.reduce((sum,d)=>sum+(timeLog[d.date]||0),0));$('studioMinutes').textContent=totalMinutes>=60?`${Math.floor(totalMinutes/60)}h ${totalMinutes%60}m`:String(totalMinutes);$('studioMinutes').nextElementSibling.textContent=totalMinutes>=60?'/ 7 ngày':'phút / 7 ngày';$('studioWeek').innerHTML=days.map(d=>{const minutes=Math.round(timeLog[d.date]||0),hours=Math.floor(minutes/60),mins=minutes%60,readable=hours?`${hours} giờ ${mins} phút`:`${mins} phút`;return `<button type="button" class="studio-week-day" data-week-date="${d.date}" aria-label="${d.date}: ${readable}"><span class="studio-bar"><i style="height:${Math.max(3,(minutes)/max*100)}%;opacity:${minutes?1:.2}"></i></span><span>${d.label}</span></button>`}).join('');$('studioWeek').querySelectorAll('[data-week-date]').forEach(b=>b.onclick=()=>{const minutes=Math.round(timeLog[b.dataset.weekDate]||0),hours=Math.floor(minutes/60),mins=minutes%60;$('studioWeekDetail').textContent=`${new Date(b.dataset.weekDate+'T12:00:00').toLocaleDateString('vi-VN',{weekday:'long',day:'2-digit',month:'2-digit'})} · ${hours?hours+' giờ ':''}${mins} phút đã học`;$('studioWeek').querySelectorAll('.studio-week-day').forEach(x=>x.classList.toggle('is-selected',x===b))});const remaining=meta.examDate?CharterPrep.dayNumber(meta.examDate)-CharterPrep.dayNumber(CharterPrep.localDay()):null;exam.innerHTML=`<span>${icons.calendar} KỲ THI SẮP TỚI</span><strong>${remaining===null?'Đặt ngày thi':Math.max(0,remaining)}${remaining!==null?'<small> ngày nữa</small>':''}</strong><span class="studio-exam-track"><i style="width:${remaining===null?0:Math.min(100,Math.max(0,(1-remaining/Math.max(meta.totalDays,1))*100))}%"></i></span><small>${meta.examDate?new Date(meta.examDate+'T12:00:00').toLocaleDateString('vi-VN'):'Cá nhân hoá kế hoạch của bạn'}</small>`}
function drawActivity(){const entries=[],byId=new Map(MODULES.map(m=>[m.id,m]));for(const [id,date]of Object.entries(meta.charterPrep?.completedAt||{})){const m=byId.get(id);if(m&&progress[id])entries.push({module:id,label:m.name,date,kind:'module',type:'Module',result:'Đã hoàn thành',tone:'good'})}for(const q of StudyLab.getState().qbank){const m=byId.get(q.moduleId);if(m)entries.push({module:m.id,label:m.name,date:q.date+'T12:00:00',kind:'practice',type:'QBank',result:`${q.correct}/${q.total} câu · ${Math.round(q.correct/q.total*100)}%`,tone:q.correct/q.total>=.7?'good':''})}for(const m of mockTests)entries.push({label:m.name,date:m.date+'T12:00:00',kind:'practice',type:'Thi thử',result:`${m.correct}/${m.total} câu · ${Math.round(m.correct/m.total*100)}%`,tone:''});const list=entries.filter(x=>activityFilter==='all'||x.kind===activityFilter).sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,6);$('studioActivity').innerHTML=list.map((r,i)=>`<tr><td><button data-studio-activity="${i}" class="studio-activity-name"><i>${icons.book}</i><span>${esc(r.label)}</span></button></td><td>${new Date(r.date).toLocaleDateString('vi-VN')}</td><td>${r.type}</td><td class="${r.tone==='good'?'studio-good':''}">${r.result}</td></tr>`).join('');$('studioActivityEmpty').hidden=!!list.length;activity.querySelector('table').hidden=!list.length;activity.querySelectorAll('[data-studio-activity]').forEach(b=>b.onclick=()=>{const r=list[Number(b.dataset.studioActivity)];r.module?CharterExperience.openModule(r.module):CharterExperience.navigate('mocks',{focus:true})});activity.querySelectorAll('[data-studio-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.studioFilter===activityFilter)))}
activity.querySelectorAll('[data-studio-filter]').forEach(b=>b.onclick=()=>{activityFilter=b.dataset.studioFilter;drawActivity()});
function drawTopics(){const qbank=StudyLab.getState().qbank;let touched=0;$('studioTopics').innerHTML=TOPICS.map((topic,index)=>{const ids=new Set(MODULES.filter(m=>m.topic===topic).map(m=>m.id)),q=qbank.filter(x=>ids.has(x.moduleId)),total=q.reduce((s,x)=>s+x.total,0),correct=q.reduce((s,x)=>s+x.correct,0),pct=total?Math.round(correct/total*100):0;if(total)touched++;return `<button class="studio-topic-row" data-studio-topic="${index}"><span>${esc(topic)}</span><small>${ids.size} module</small><span class="studio-topic-track"><i style="width:${pct}%"></i></span><span class="studio-topic-result">${total?pct+'%':'Chưa luyện'}</span></button>`}).join('')||'<p class="studio-empty-note">Chương trình chưa có module. Thêm bài trong Cài đặt để bắt đầu.</p>';$('studioTopicsCount').textContent=`${touched}/${TOPICS.length} môn có kết quả QBank`;$('studioTopics').querySelectorAll('[data-studio-topic]').forEach(b=>b.onclick=()=>jumpToTopic(TOPICS[Number(b.dataset.studioTopic)]))}
function draw(){drawStats();drawActivity();drawTopics()}
const previousRender=render;render=function(){previousRender();draw()};const previousCommit=$('cpTimerCommit').onclick;$('cpTimerCommit').onclick=()=>{previousCommit();drawStats()};
const labels={today:'Trang chính',modules:'Module học',practice:'Luyện tập',cards:'Thẻ nhớ',roadmap:'Lộ trình',schedule:'Lịch học',review:'Ôn tập',mocks:'Thi thử',analytics:'Thống kê',journal:'Nhật ký',settings:'Cài đặt'};
function route(){const id=CharterExperience.getRoute();document.body.dataset.studyRoute=id;root.querySelector('.header h1').textContent=labels[id]||'CharterPrep';$('uxBreadcrumb').textContent=labels[id]||'Trang chính'}
addEventListener('charter-route',route);route();draw();
root.querySelectorAll('[data-ux-route="today"] .nav-label').forEach(n=>n.textContent='Trang chính');
function normalizeWeekBars(){const week=$('studioWeek');week?.querySelectorAll(':scope>button[data-week-date]').forEach(b=>{const wrap=document.createElement('div');wrap.className='studio-week-day-wrap';b.parentNode.insertBefore(wrap,b);wrap.appendChild(b)})}normalizeWeekBars();new MutationObserver(normalizeWeekBars).observe($('studioWeek'),{childList:true});
window.StudyStudio={draw,getActivityFilter:()=>activityFilter};
})();
